### ISSUE TITLE
Allow any type for arg when options.skip is true in use*Query

### ISSUE THREAD

**Issue by rabidpug** [rtk-incubator/rtk-query#101]
When I'm using the `skip` option in a use*Query hook it currently gives a type error:

```js
{
  user: builder.query<User,User['id']>({ query: (id) => `user/${id}`} ),
}
....
const { data, error } = useQuery(id, { skip: !id }) // Type 'string | undefined' is not assignable to type 'string'.
```

Would be handy if the type could be anything when `skip` is true.

**Comment by msutkowski** [comment]
Hey @rabidpug, thanks for trying out rtk query! `skip` expects a boolean so that should work. but it looks like that type error is coming from the `id` property, not `skip`. 

I imagine in your types for `User` you have `id: string`, and then wherever you're setting types for `id` in the component, you have `id: string|undefined`. You can fix the types there, or you can do the following being that you know id would exist when skip evaluated to true:

`const { data, error } = useQuery(id!, { skip: !id })`

**Comment by rabidpug** [comment]
Hi @msutkowski,
Yes sorry I mustn't have been clear in my first post - by "arg" I meant the first parameter for use*Query. IE don't enforce the type of the first parameter if option.skip is true
I wouldn't want to change the type for id to atring|undefined as undefined isn't a valid value for id - unless option.skip is true, because when option.skip is true id isn't being used.
Would it be possible to have an overload for the type definition for use*Query when skip = true?

**Comment by phryneas** [comment]
I think making it potentially `undefined` might be a good call, but not something completely else.
I'll put it on my TODO list

**Comment by rabidpug** [comment]
Thanks @phryneas for picking it up! Much appreciated

My 2c for why it should be `any` (or as relaxed as possible) would be because it is unused, so it *can* be absolutely anything and nothing bad will happen. So from a type safety perspective, specifically requiring `ArgType | undefined` is unnecessarily restrictive, and may encourage lazy & unsafe type overrides by the user to avoid writing `skip ? undefined : args` all over a project, especially in instances where the argument is an object where one or more of its values may be undefined (and thus the query would be skipped)

**Comment by phryneas** [comment]
But realistically: what other value would that be? I can see `undefined` and maybe `null`, but if you have a completely different value in there, that seems a bit like a code smell.

Also, this might not really be useful at all.
I just experimented a bit in [this codesandbox](https://www.typescriptlang.org/play?target=7#code/GYVwdgxgLglg9mABCAzgUwIojQJwJ4AUAHgFyICGYeANInAA5QpkDeiKA1jPWVDtogC+iAJRkAbnBgATAFChIsBMnRZchUuz4wwAc1oMmrdlx6Jg5ADbohoiVLkLo8JKkzZ8xMim17EAH2QwaTRgHTRpA0ZmRDZObjIAIzg4SzRKWxEWQVlZEIhLchw0RAgEH0RNHxwdXQCgkLCwCIBuXIB6dooUREsEOvIegAN4+iHEGB6QqFwAW3DpRGk8MHJ5iCtLGkQoAAtJiZ6wOCg6YERZkAhdxHErbFk3NU8iWhZR3jx6NDhzokQAIQAXiBiAARNVamChCI2o9VB4NG8Pjt+CVBLDZJ1EAABJgAWjQRG+0EJOBwcBw8Pc6mIyNMZAs1nRmKAA) and if you want to determine `skip` dynamically, TS won't make a connection between the arguments.

So something like `useQuery(x, {skip: typeof x !== "string" });` will never work. No matter if it's `| undefined` or just `any` for `x`.

**Comment by phryneas** [comment]
This will be adressed in https://github.com/reduxjs/redux-toolkit/pull/1056
