### ISSUE TITLE
createApi.enhance (or similar)

### ISSUE THREAD

**Issue by phryneas** [rtk-incubator/rtk-query#104]
I'm thinking of splitting the react-specific stuff out, so we will probably have stuff like

* createApi.enhance(enhancer)
* enhanceWithHooks(options)
* createReactapi = createApi.enhance(enhanceWithHooks(options))

which would open the door for other enhancers for other frameworks and would allow us to ship a non-react-version of this for smaller bundle size in other frameworks.

Adding the custom context to the `options` for `enhanceWithHooks` would be a lot easier as that point than trying to get it in right now.

_Originally posted by @phryneas in https://github.com/rtk-incubator/rtk-query/issues/92#issuecomment-740150272_

**Comment by markerikson** [comment]
What's `.enhance` supposed to do?

**Comment by phryneas** [comment]
Basic `createApi` would be `createApi` without any hooks etc.
`.enhance` would return a new `createApi` with the enhancer baked in, so in this example, the react hooks.
Or down the line, react HOCs, react renderProps, svelte helpers, vuejs providers etc.
Of course, enhancing multple times would be possible. Also, we would build additional entry points with pre-configured `createApi` versions.

This would allow us to support all these different targets with good tree-shaking support.

**Comment by kahirokunn** [comment]
This is great idea!

**Comment by phryneas** [comment]
This was actually already done in #116, but with a slightly different API than I had imagined initially. Closing this one :)
