### ISSUE TITLE
Even if the API returns a 404, Promise is still resolved.

### ISSUE THREAD

**Issue by kahirokunn** [rtk-incubator/rtk-query#114]
https://rtk-query-docs.netlify.app/concepts/mutations#basic-mutation
So never come catch section 😢 

The resolved values look something like this.

<img width="430" alt="スクリーンショット 2020-12-16 13 15 51" src="https://user-images.githubusercontent.com/22343391/102304578-1fc1a100-3fa1-11eb-87aa-88036b94b750.png">

**Comment by phryneas** [comment]
This is an error action. 
The next time the component renders, `result.isError` will be true and the error will be in `result.error`. 
We deliberately do not throw a promise rejection as that would cause a "uncaught promise rejection" error for everyone who does not `.catch` the rejection - which would be the case for almost all users, as this API is not really meant for you to catch it, or wait on the promise in the first place.
You *can* do so if you really want to though, but then you have to check for yourself if it is a `fulfilled` or `rejected` action. You can do so by using [unwrapResult](https://redux-toolkit.js.org/api/createAsyncThunk#unwrapping-result-actions) - but again, that's not really something you'd usually do.

**Comment by Aloysb** [comment]
Interesting, had the same issue - I thought 

In the mutation section of the docs, it shows the usage of catch

```js
      onUpdate={(name) => {
          return (
            // Execute the trigger with the `id` and updated `name`
            updatePost({ id, name })
              .then((result) => {
                // Do something with the result
                console.log('Update Result', result);
              })
              .catch((error) => console.error('Update Error', error))
          );
        }}
        ```

**Comment by phryneas** [comment]
Good catch, gotta fix the docs there :+1:

**Comment by Aloysb** [comment]
@kahirokunn you can use the snippet:

```js
export const customApi = createApi({
  baseQuery: fetchBaseQuery({ baseUrl: '/api/' }), // Set the baseUrl for every endpoint below
  endpoints: (builder) => ({
    getUsers: builder.query({
      query: () => ({
        url: `users`,
        validateStatus: (response) => response.status >= 200 && response.status <= 300 
      }),
    }),
  }),
});
```
Note the `validateStatus` property.
Only drawback is that you'll have to set it on every queries/mutations, there might be a solution to do it globally, similar to interceptors, but I haven't found it .. Or maybe use Axios (but I haven't had any luck myself making it work with RTK Query).

FetchBaseQuery is based on fetch, which doesn't reject the promise as long as the API answers (unlike Axios)

**Comment by Aloysb** [comment]
@phryneas AHA! I understand now. Been using it not the way it's been designed, which didn't help.

**Comment by kahirokunn** [comment]
I didn't actually want the Promise to be rejected in this case.
I'm just reporting that I followed the document sample and got a different behavior than what the sample expects.

**Comment by msutkowski** [comment]
@kahirokunn If you checkout the next branch and it's docs previews, or use one of the latest builds, this has been addressed and will be released later this week (tentatively the 26th):

```
 "@rtk-incubator/rtk-query": "https://pkg.csb.dev/rtk-incubator/rtk-query/commit/7053399d/@rtk-incubator/rtk-query",
```

The examples and such have been updated as well per this issue. In general, you can use a type guard/matcher to narrow the types down. As an example, I'm doing this in combination with the new `.unwrap()` API alongside `fetchBaseQuery`:

```ts
const [updateUser] = useUpdateUserMutation();

try {
      await updateUser(values).unwrap();

      redirectByStatus();
    } catch (err) {
      if (isMyKnownError(err)) {
        const msg = err.data.message;
        if (msg.includes('is not a valid phone number')) {
          return setFieldError('phone', msg);
        }
      }
    }
 ```

In your case, you could do something like:

```ts
     const resultAction = await updateUser(values);

      if (isMyKnownError(resultAction.error)) {
        const msg = resultAction.error.data.message;
        if (msg.includes('is not a valid phone number')) {
          setFieldError('phone', msg);
        }
      }
    }
```

**Comment by kahirokunn** [comment]
I see.
That's awesome !!
