### ISSUE TITLE
ValidateStatus => unable to validate response as per documentation

### ISSUE THREAD

**Issue by Aloysb** [rtk-incubator/rtk-query#122]
The following mutation gets rejected (I've rewritten it several times to ensure it works, this one is a coming from the docs):

```js
 stripRoute: builder.mutation({
      query({ key }) {
        return {
          url: `routeBook/strip/${key}`,
          method: "PUT",
        };
      },
      invalidates: ["Routes"],
    }),
 ```
 
 Action:
 ```js
 {
  meta: {
    arg: {
      endpoint: 'stripRoute',
      internalQueryArgs: {
        url: 'routeBook/strip/27',
        method: 'PUT'
      },
      originalArgs: {
        key: 27
      },
      track: true,
      startedTimeStamp: 1608296390672
    },
    requestId: 'BZt7va1eGOpVeMNEXYbX9',
    rejectedWithValue: false,
    requestStatus: 'rejected',
    aborted: false,
    condition: false
  }
}
```

But the API is hit and updated, however the mutation returns 'rejected' which in turns doesn't trigger the invalidation.

**Comment by Aloysb** [comment]
And the error from the devTools.

```js
error{
  "name": "SyntaxError",
  "message": "Unexpected end of JSON input",
  "stack": "SyntaxError: Unexpected end of JSON input"
}
```

I'm unusure why. Other mutations seem to be working fine.

**Comment by Aloysb** [comment]
PS: As a work around, I am just forcing the 'refetch' on this particular Mutation, just curious to understand why it doesn't work.

I think the Mutation might gets reject because it doesn't return a body (204) (c.f. [expected response](https://rtk-query-docs.netlify.app/concepts/error-handling)). So it might be normal behaviour.

I tried to force the validation of the mutation by adding:
```js
validateStatus: (response) => response.status === 200
```

Did not work though.

**Comment by phryneas** [comment]
That sounds like https://github.com/rtk-incubator/rtk-query/issues/89

You can use the current dev build from https://ci.codesandbox.io/status/rtk-incubator/rtk-query/pr/1 that already includes a patch.

**Comment by Aloysb** [comment]
That's right, same issue.

I'll close this.
However, why the validateStatus function wouldn't 'force' its way through?

**Comment by phryneas** [comment]
no matter if you validate or not, if the parsing of the response literally crashes, it wasn't successful as you're not able to access the result.
