### ISSUE TITLE
Testing -  TypeError: Cannot read property 'mutations' of undefined     

### ISSUE THREAD

**Issue by Aloysb** [rtk-incubator/rtk-query#125]
I was wondering if you have any guidance when it comes to testing.
I tried to mock the Query hooks without any success.

Cheers.
Keep up the good work 👍

**Comment by phryneas** [comment]
Best use a tool like https://github.com/mswjs/msw to really mock the API endpoints

**Comment by Aloysb** [comment]
Thanks @phryneas I'll make sure to check them out.

**Comment by Aloysb** [comment]
@phryneas 
MSW is indeed extremely handy, but I fail to use it with RTK Query:

Using  a regular fetch or axios request does the trick, but as soon as I use a mutation issued from RTK Query my test fails:

```
 TypeError: Cannot read property 'mutations' of undefined                                                                                                                              
                                                                                                                                                                                          
      at node_modules/@rtk-incubator/rtk-query/src/buildSelectors.ts:106:68                                                                                                               
      at node_modules/reselect/lib/index.js:76:25                                                                                                                                         
      at node_modules/reselect/lib/index.js:36:25                                                                                                                                         
      at node_modules/reselect/lib/index.js:90:33                                                                                                                                         
      at node_modules/reselect/lib/index.js:36:25                                                                                                                                         
      at node_modules/reselect/lib/index.js:86:37                                                                                                                                         
      at node_modules/reselect/lib/index.js:36:25                                                                                                                                         
      at node_modules/@rtk-incubator/rtk-query/src/buildActionMaps.ts:142:31
      ```
      
 Do you have any hint about how to solve this?

**Comment by Aloysb** [comment]
I think this might be the way my testProvider (i.e. 'redux' context in my test is set up).

I will try again with a 'mocked' store setup similar to this:
https://github.com/rtk-incubator/rtk-query/blob/next/test/helpers.tsx

I'll let you know.

**Comment by phryneas** [comment]
That error message reads as if the reducer were not included in that state.
Could you provide a CSB? I'd like to take a look.

As for the codesandboxes: there are no tests in there, but all APIs that are accessed by the example sandboxes are 100% faked by MSW, there is no real API.

**Comment by Aloysb** [comment]
Yes, it's indeed the case.

I'm just going to run a few more tests and post my solution here, I intend to use the actual 'real' store, so these unit tests will be somehow integration tests.

Thanks for the heads up.

**Comment by msutkowski** [comment]
@Aloysb They should be almost equivalent. For the case that you'd check actions in called orders, you can do that with a dispatch spy, but ultimately you shouldn't need to. 

I don't believe `redux-mock-store` catches any network requests, but I could be wrong. If you showed the code for some of your tests, we could give you better insight there

**Comment by Aloysb** [comment]
Thanks,
The issue state above is sorted out.

The only interrogation left, is: How would go about checking the arguments passed to the mutation ?

In the example below, I'm just calling a verification email endpoint, passing it a key and an email. How can you actually check these ?
Not the best example, but for example in a case of a form how could you make sure that the right data is passed to the mutation?

I've removed the mocked store and just use a copy of the store, in collaboration with MSW for the network requests.
Everything is working as expected.

This are my testProvider (to provide a copy of the store to the tests):

```js
export const testStore = configureStore({
  reducer: appReducer,
  middleware: (gdm) =>
    gdm({ serializableCheck: false, immutableCheck: false }).concat(
      api.middleware
    ),
});

export const testProvider = (ui, store) => {
  const history = createMemoryHistory();
  return (
    <Provider store={store}>
      <Router history={history}>{ui}</Router>
    </Provider>
  );
};
```

And this is a test example:

```js
import React from "react";
import "@testing-library/jest-dom";
import { testStore, testProvider } from "~/mocks/utils";
import {
  screen,
  act,
  render,
} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import EmailVerification from "./EmailVerification";
import "whatwg-fetch";
import { server } from "~/mocks/server";
import { rest } from "msw";
import { APIEndpoint } from "~/api/config";

describe("<Email verification />", () => {

  beforeEach(() => render(testProvider(<EmailVerification />, testStore)));
  
it("on successful email verification, it displays a success message with a link to login", async () => {

    const verifyButton = screen.getByRole("button", { name: /email/i });

    await act(async () => {
      userEvent.click(verifyButton);
    });

    expect(
      await screen.findByRole("alert", { name: /success/i })
    ).toBeInTheDocument();
    expect(
      await screen.findByRole("link", { name: /login/i })
    ).toBeInTheDocument();
  });

  it("on error, there's an error message and a button to try again", async () => {
  
   //MSW configuration returns a success 204 response, this override it to simulate a failed request.
    server.use(
      rest.put(
        `${APIEndpoint}/membership/validate-email/:key/:email`,
        (req, res, ctx) => {
          return res(ctx.status(422));
        }
      )
    );
    
    const verifyButton = screen.getByRole("button", { name: /email/i });

    await act(async () => {
      userEvent.click(verifyButton);
    });

    expect(
      await screen.findByRole("alert", { name: /error/i })
    ).toBeInTheDocument();
  });
})

**Comment by msutkowski** [comment]
@Aloysb Sorry, I've been on vacation and didn't see this until just now. A few things:

You don't need to wrap `userEvent.click` with act, as it's already wrapped with act - https://twitter.com/kentcdodds/status/1330937800321974272?lang=en

Regarding checking the arguments passed, there are a handful of ways to do that. I wouldn't focus on testing the implementation details of `baseQuery` itself... one trick we use with MSW is to just echo the original request. You can see an example of that here: https://github.com/rtk-incubator/rtk-query/blob/next/test/fetchBaseQuery.test.tsx#L116-L135

**Comment by Aloysb** [comment]
@msutkowski No worries at all!

Thanks for these advices they're are greatly appreciated. Testing isn't my forte. Thank you.
