### ISSUE TITLE
Allow specifying `queryFn` in endpoint definitions to skip `baseQuery`?

### ISSUE THREAD

**Issue by phryneas** [rtk-incubator/rtk-query#139]
Inspired by https://www.reddit.com/r/reactjs/comments/kkq8bi/alpha_2_of_rtkquery_released/ghovnvh/?context=3

This would allow endpoints to get a `queryFn` option that would replace & skip the `baseQuery` for that endpoint. `query` would become optional in that case and default to `x => x`.

That way, stuff like the google api client, or maybe firebase, could just be used as asynchronous functions.

From the codebase and our internal workflows it should be feasible to implement without too many changes.

Any thoughts?

**Comment by utkarshgupta137** [comment]
To add this, I have some like [this](https://github.com/utkarshgupta137/youtube-playlist-manager/blob/v0.2.0/src/containers/Playlists/playlistsSlice.js#L85). Here, fetchPlaylistItems is calling fetchVideos with its result, which then does its thing & updates the state.

As far as I can tell, there is no straightforward way to do this with the current flow. Having the option to use our own functions will make it much easier to do this.

Also, IMO, the library should be agnostic to the fetching part in-general, and the current baseQuery/query should be like an opinionated way of doing things (or like a wrapper for doing away with repetitive code) as a separate `createOpinionatedApi`. This will also remove the need for `selectFromResult`. I guess I'm asking for a more react-query like behaviour.
