### ISSUE TITLE
How can I add a reducer for api/executeQuery/rejected ?

### ISSUE THREAD

**Issue by kahirokunn** [rtk-incubator/rtk-query#143]
I just want to handle all some http status code. 👀  (ex. 403

I couldn't find a way to do this from the current document.
Would you like to be able to write code like this?

```typescript
builder
        .addCase(api.rejected, (state, { meta: { arg, requestId } }) => {
          // do something
        })
```

**Comment by msutkowski** [comment]
@kahirokunn There is some [information about matchers here](https://rtk-query-docs.netlify.app/concepts/error-handling/#handling-errors-at-a-macro-level) as well as [here](https://rtk-query-docs.netlify.app/api/createapi/#action-matchers).

You would want to use [`addMatcher` from RTK](https://redux-toolkit.js.org/api/createReducer#builderaddmatcher) for this behavior. I can't tell exactly what you want to do from the question, but you can easily sort this out with matches :)

**Comment by kahirokunn** [comment]
This is what I've been looking for!
Thx!
