### ISSUE TITLE
support AsyncThunkAction.

### ISSUE THREAD

**Issue by kahirokunn** [rtk-incubator/rtk-query#149]
I got a type error when I tried to pass AsyncThunkAction to dispatch, do you feel that this is the intention?

```typescript
onStart(arg, { dispatch }) {
  const action = someAsyncThunk('hello world')
  dispatch(action)
}
```

If this is not intended, I'll throw a pull request to change it to Dispatch<any>. What do you think?

**Comment by kahirokunn** [comment]
I get an error when I pass AsyncThunkAction.
How can I make it work? 😢

**Comment by phryneas** [comment]
I think we could savely change the type of that `disptach` from `Dispatch` to `ThunkDispatch<any, any, AnyAction>` or something similar there.

**Comment by kahirokunn** [comment]
I see.
I'll try to modify it that way！

**Comment by kahirokunn** [comment]
@phryneas https://github.com/rtk-incubator/rtk-query/pull/150
is like this?
