### ISSUE TITLE
How to dynamically add entityTypes?

### ISSUE THREAD

**Issue by kahirokunn** [rtk-incubator/rtk-query#153]
In the api instance generated by rtk-query-codegen, entityTypes is empty by default.

If you want to add or modify endpoints dynamically by using libraries, you may want to add entityTypes.

What should I do in this case?

**Comment by msutkowski** [comment]
Hmm, i tried to link the docs, but they broke... This should be documented here: https://rtk-query-docs.netlify.app/concepts/code-generation#openapi. You're looking for 'addEntityTypes' of `enhanceEndpoints` if it doesn't link properly.

**Comment by kahirokunn** [comment]
It worked!
Thank you!
