### ISSUE TITLE
Optimistically deleting an entity?

### ISSUE THREAD

**Issue by colemars** [rtk-incubator/rtk-query#159]
`patchQueryResults` and `updateQueryResult` make sense to me with regards to Update mutations. But I can't tell if optimistically deleting an entity is possible in a similar manner?

Referring to this area in the docs: https://rtk-query-docs.netlify.app/concepts/optimistic-updates

**Comment by phryneas** [comment]
Do you mean deleting a whole cache key or deleting part of something cached?

The first doesn't really make sense - rtk-query will handle that in 60 seconds anyways and you don't know where else it is used.

As for the other thing, the example might not be clear enough: you can do *everything* within that other result:

```js
          api.util.updateQueryResult('getPost', id, (draft) => {
            delete draft.foo;
            draft.bar = "hahaha"
          })
```

**Comment by colemars** [comment]
ahh okay yeah that helps! Thank you.
