### ISSUE TITLE
Actions returned by createApi

### ISSUE THREAD

**Issue by Sun-2** [rtk-incubator/rtk-query#161]
`createApi` so far returns `internalActions`.

 Is there ever going to be a stable public API for it, for use in Sagas, for example?

**Comment by phryneas** [comment]
Which actions do you want to use in sagas explicitly? 

Most of the actions in there are pretty clunky to use, usually you probably want to use the action matchers under `api.endpoints.x.matchPending` etc, which work just fine in sagas.

**Comment by Sun-2** [comment]
Mostly initiating a fetch inside a saga.

**Comment by phryneas** [comment]
It might be good if you explain what you want to do with more than seven words.

Do you want to react to some internal action in a saga and do your own fetch which will be handled as part of your own redux store? Why are `api.endpoints.x.match*` not enough for you?

Do you want to trigger rtk-query to fetch some data? Why is `api.endpoints.x.initiate` not enough for you?

Do you want to do something completely different? I have no idea.

**Comment by Sun-2** [comment]
Hi,

I'm sorry, somehow in my blindness I did not notice the `initiate` method. Coupled with the `match*` methods, it makes it possible to cleanly do everything I wanted to do (which is pretty much what you described). 

That's all, thank you for your answer. I'll close this issue.
