### ISSUE TITLE
can I receive notification "is revalidate completed"?

### ISSUE THREAD

**Issue by kahirokunn** [rtk-incubator/rtk-query#165]
I love the invalidates experience!
I now use this feature on a daily basis!

By the way, in the following code, even if I get `success update my name`, `data.myName` will remain at the value before the update for a while.
I would like to send out a toast when the revalidate of `api.endpoints.getMyName` is completed. (For example, is there a function to receive a notification when the revalidate is completed?

```ts
api.enhanceEndpoints({
  addEntityTypes: ['MyName', 'B', 'C'],
  endpoints: {
    getMyName: { provides: ['MyName'] },
    updateMyName: { invalidates: ['MyName'] },
  },
});

function SomeComponent() {
  const { data, isLoading } = api.endpoints.getMyName.useQuery()
  const [updateMyName] = api.endpoints.updateMyName.useMutation()
  const [toast] = useToast()

  const handleSubmit = async () => {
    await updateMyName({
      updateMyNameParams: {
        myName: 'Pikachu'
      }
    })
    toast.success('success update my name')
  }

  if (isLoading) {
    return <div>Loading...</div>
  }

  return (
    <>
      <h2>{data.myName}</h2>
      <button onClick={handleSubmit}>update my name</button>
    </>
  )
}
```

**Comment by phryneas** [comment]
I'm closing everything here now. If there's any need for further discussion, that should take place in a new issue over at https://github.com/reduxjs/redux-toolkit/
