### ISSUE TITLE
How to handle blob ?

### ISSUE THREAD

**Issue by gfortaine** [rtk-incubator/rtk-query#169]
It looks like that blob is not serializable (see #154). How could we handle it ? Here is our current workaround by using [URL.createObjectURL](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL) :

https://github.com/gfortaine/rtk-query-nextjs-example/tree/responseHandler/blob

```js
responseHandler: (response) => response.blob().then(blob => URL.createObjectURL(blob))

**Comment by phryneas** [comment]
Well, rtk-query stores those values in the redux store, as any other solution using redux as a cache would do. So it comes down to basic redux at this point.

So you have essentially the two options:
* serialize the values before storing them (as you do there)
* break the best practice of not storing non-serializable data in redux and disable the warning. Depending on the middleware and tooling you are using, that might work or be problematic. 

Either way, this is probably a choice that should be made individually - I don't think that we should do anything by default in rtk-query here.
