### ISSUE TITLE
invalidation not triggering cached rejected fetches 

### ISSUE THREAD

**Issue by Kirbyasdf** [rtk-incubator/rtk-query#170]
okay it seems as though the provide/invalidates is not behaving correcting since my initial fetch fails ,

currently when a user loads the app , the autheticateQuery hook will trigger, app.js, however it will return a 401 (_as the user is not logged in)_ and rtk query will set it to rejected.... then when they login, nothing happens....however if they reload the app it will fire again and redirect them to the private route..... and then if they log out, app brings them back to public routes and then if they log in again _(without refreshing) it will work as intended ... .

now the authquery is provided by the invalidation of the login and register mutations, however I believe that it only works once the user has refreshed the app is because for some reason RTK query will not refetch a failed request....

I believe that the failed 401 request is being cached and therefor even with the hook being mounted and provided by login it will not trigger, otherwise I can not see why it would not fire when it does perfectly fine after 1 successful request

 **is there some way to fix this ?**
 
If there is no fix currently can I suggest several options to the builder? : 

1. an option for refetch irregardless of cache, or at least upon certain parameters such as  response codes etc
2. an option for refetch on any state change, globally or specific states 
3. a timeout b4 refetch.. .I know there is currently an option for a refetch, however this would take more of a load off of component based logic for fetching at certain intervals 
4. built in middleware for tracking general fetches, along the lines of what is used in the initial demo videos: which I believe was custom built
5. on each query, an option to use or not use such options as prepareHeaders from the fetchBaseQuery object or any other settings and either revert to default or their own written in the builder

for reference here is the code for the api  + comps:  app / login
[repo :](https://github.com/Kirbyasdf/React-Redux-Socket-SQL-NODE)

src/services 
**api.js**

```js
import { createApi, fetchBaseQuery } from "@rtk-incubator/rtk-query";
import { RootState } from "../redux/store";

const { REACT_APP_BASE_URL } = process.env;

const baseQuery = fetchBaseQuery({
	baseUrl: REACT_APP_BASE_URL,
	prepareHeaders: (headers) => {
		const token = RootState().auth?.token;
		if (token) {
			headers.set("authorization", `Bearer ${token}`);
		}
		return headers;
	},
});

export const api = createApi({
	reducerPath: "authQuery",
	baseQuery,
	entityTypes: ["Auth"],
	endpoints: (builder) => ({
		authenticate: builder.query({
			query: () => `/auth`,
			provides: ["Auth"],
		}),
		login: builder.mutation({
			query: (form) => ({
				url: "auth/login",
				method: "POST",
				body: form,
			}),
			invalidates: ["Auth"],
		}),
		register: builder.mutation({
			query: (form) => ({
				url: "auth/register",
				method: "POST",
				body: form,
			}),
			invalidates: ["Auth"],
		}),
	}),
});

export const { useAuthenticateQuery, useLoginMutation, useRegisterMutation } = api;

export const {
	endpoints: { login },
} = api;
```
src/
**App.js**

```js
export const App = () => {
	useAuthenticateQuery();
	return (
		<Switch>
			<Route exact path="/" component={Chat} />
			<Route path="/login" component={Login} />
			<Route path="/register" component={Register} />
			<PrivateRoute path="/private" component={PrivatePage} />
			<Route render={() => <h1>404 not found</h1>} />
		</Switch>
	);
};

```
src/components/auth
**Login.js**

```js
	useEffect(() => {
		if (isAuthenticated) {
			return history.replace("/private");
		}
	}, [isAuthenticated]);

	const submitForm = async (e) => {
		e.preventDefault();
		login(form);
	};
```

**Comment by phryneas** [comment]
Hmm. The thing is that we currently don't take `provides` into account for rejected queries because the callback function could not be called with the result. But I guess we'll have to find a way around that.  I'll do some experimentation.

**Comment by chknwaffles** [comment]
@phryneas is it possible to get a timeframe update on this?
thanks!

**Comment by phryneas** [comment]
I'll probably be able to look into that in a little over a week. Got a lot going on right now, so I don't have too much time, sorry.

**Comment by phryneas** [comment]
So, essentially we have 3 options, all changes apply to `invalidates` and `provides`:

1. The non-function notation fires on success and error. The function notation fires always, signature changes from `(result) => stuff` to  `(result?, error?) => stuff`
2. Everything stays as it is, but we add additional `invalidateOnError` and `provideOnError` properties
3. Like 1, but change the signature to `({ error: Error; data?: undefined } | { error?: undefined; data?: Result }) => stuff`


No 2. Would be the most compatible, while 1 and 3 would be breaking changes. 

No 3. is the most breaking change, but also the most clear with other notations we use

No 1. is a good balance - a bit breaking, but we don't have to rewrite all the examples & docs in-depth, but just smaller changes. So for now I'm preferring that one.

@msutkowski do you have any thoughts on this?

**Comment by msutkowski** [comment]
@phryneas I agree on #1.

**Comment by ArslanInfinite** [comment]
@phryneas can you please describe the new syntax for this when compared to the original opening comment of Feb 17th. Thank you

**Comment by phryneas** [comment]
Quoting #180:

> It is at the moment of writing a breaking change as it changes the signature of invalidates/provides from (result, args) => Entities to (result?, error?, args) => Entities.
> 
> It only triggers on handled errors, which means a simple throw in the baseQuery would pass by this, only an error returned by returning { error: ... } from baseQuery would lead to this.

Please note that this is not merged yet. If you want to use it you have to use the CodeSandbox build from #180. (And please give feedback there)

**Comment by tevariou** [comment]
Couldn't this be handled by skipping `useAuthenticateQuery()` if the user is not yet logged in ? What's the point of firing a request at this point ?

**Comment by phryneas** [comment]
@tevariou it would also not be re-fired after login, while otherwise it could just `provide` a `{ type: "AUTHENTICATED_CONTENT" }` that would be invalidated on a login mutation.
