### ISSUE TITLE
I want a selector like react-redux for optimize the number of renders.

### ISSUE THREAD

**Issue by kahirokunn** [rtk-incubator/rtk-query#184]
What do you think?

**Comment by phryneas** [comment]
https://rtk-query-docs.netlify.app/concepts/queries#selecting-data-from-a-query-result ?

**Comment by kahirokunn** [comment]
Yes!
If I want to reduce the number of renders for mutation as well, you need to create a pull request for mutation, right?

**Comment by phryneas** [comment]
Yeah, we'd need a PR on that. It would be a great addition if you could look into that.

**Comment by msutkowski** [comment]
@kahirokunn Did you have any interest in putting up a PR for this? If not, I will try to get to it this weekend. Thanks!

**Comment by kahirokunn** [comment]
I'm sorry I didn't move sooner!
I'll do it because it sounds like fun!

**Comment by kahirokunn** [comment]
@msutkowski I tried to write it using `useQueryState` as a reference, but I couldn't find the part in `useQueryState` that calculates the `type` according to the value of `selectFromResult`, so can I ask useMutation to implement `selectFromResult`?

**Comment by kahirokunn** [comment]
I understand now!
I'll try again!
