### ISSUE TITLE
Support for GraphQL subscriptions

### ISSUE THREAD

**Issue by dutzi** [rtk-incubator/rtk-query#186]
Hey, I couldn't find documentation for using GraphQL subscription-based data fetching.

I am not sure on which layer this should rest. Whether or not it should be the responsibility of the user (inside the application's code) or the framework's (RTK Query), a decent example would be very helpful.

Thank you

**Comment by phryneas** [comment]
I'm sorry, I kinda missed this issue.

Right now, it's a bit complicated, as you need to make a query first to get a cache entry and then need to keep it updated somehow.
You can modify existing cache values using
```js
dispatch(
          api.util.updateQueryResult('someEndpoint', arg, (draft) => {
            draft.foo.bar = "asd"
          })
        )
```

It might get a bit easier once we have https://github.com/rtk-incubator/rtk-query/pull/158 in, so you could initiate a connection to your server directly in your queryFn, but it would still not be optimal as you could not detect from there if a query state gets stale & removed from the state.


Probably the best would be the combination of a normal query with a middleware that looked something like this:

```js
const subscriptionMiddleware = middlewareApi => next => action => {
  if (api.endpoint.myEndpoint.matchFulfilled()(action)) {
    // start subscription for myEndpoint with arg action.meta.arg.originalArgs, track somehow as action.meta.arg.queryCacheKey
    //  regularly update using api.util.updateQueryResult
  }
  if (api.internalActions.removeQueryResult.match(action)) {
    // stop subscription tracked as action.payload.queryCacheKey
  }
}
```

But yah, tbh this is not reaaaally a core use case :sweat_smile:

**Comment by dutzi** [comment]
@phryneas, no worries! I appreciate your elaborated explanation.

I ended up writing a hook the kind of does the same as you suggested. Given an endpoint's "name", i.e., its key, it will set up a listener and dispatch `api.util.updateQueryResult` when needed.

Eventually, I realized "simple" cache-invalidation is a better solution for my needs after having done that 😬.

**Comment by phryneas** [comment]
@dutzi  Could you give an opinion on this please? https://github.com/rtk-incubator/rtk-query/issues/215
