### ISSUE TITLE
Would be great if there was a possibility to access the response headers

### ISSUE THREAD

**Issue by LuukvH** [rtk-incubator/rtk-query#194]

**Comment by phryneas** [comment]
This is possible by providing your own `baseQuery`, but currently we do not have such information available as part of the `fetchBaseQuery`.

You can see a very simple `baseQuery` implementation in the graphql example: https://rtk-query-docs.netlify.app/examples/react-with-graphql

https://github.com/rtk-incubator/rtk-query/blob/next/src/fetchBaseQuery.ts


We *could* think about adding an optional `meta` field to the BaseQuery response and make that available only in the `transformResponse` callback. That would cover this use case - what do you think @msutkowski ?

**Comment by msutkowski** [comment]
Hmm, I think I'd like to know more about the use case for this. Where/when/why are they needed? It's easy enough to pass them through, but I wonder if there is value to keeping the values in state for any reason _(or is that the point of passing them to transform response to store as part of the result data?)_? The only use case I've ever really seen for response headers is if there is some type of max retries header in them.

**Comment by msutkowski** [comment]
@LuukvH Can you provide your use case here, or how you'd imagine this working?

**Comment by LuukvH** [comment]
I am working with a proxy that parses a jwt envelope and put information in the headers. For example the current tenant and request_id. An other use case i am facing is Pagination through link headers [rfc2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2)

**Comment by tobybaratta** [comment]
For the headers, there also is the use case of needing "Location" or "Content-Location" (or if you have to deal with anything MSFT, 'operation-location') back, as well as the "retry-after" time to handle retries separately.  I could see "Last-Modified" being useful as well.

**Comment by msutkowski** [comment]
> For the headers, there also is the use case of needing "Location" or "Content-Location" (or if you have to deal with anything MSFT, 'operation-location') back, as well as the "retry-after" time to handle retries separately. I could see "Last-Modified" being useful as well.

The point about 'retry-after' is interesting. I think it's possible to put together a solution for that [with this PR](#196), but it wouldn't exactly play nicely with our `retry` util — although, I doubt that matters. Someone could inspect the headers and then could just `setTimeout(() => api.dispatch(endpoint.initiate(arg)), timeoutFromHeader)` in `onError`. Is that how you'd imagine this being used? The only strange thing about this would be that a query would be in an error state on RTK Query's end, but in reality, should have some state like 'is-pending-update' and would be lost to the library.

**Comment by phryneas** [comment]
Yeah, but someone could write their own `retry` wrapper, since `meta` is the return value of the wrapped baseQuery, that new wrapper could access it and do retries as requested by the server.

**Comment by msutkowski** [comment]
> Yeah, but someone could write their own `retry` wrapper, since `meta` is the return value of the wrapped baseQuery, that new wrapper could access it and do retries as requested by the server.

True! Would it ever be relevant for an application state to know if 'endpoint X is scheduled to retry'?

**Comment by phryneas** [comment]
I don't see that really, and if it would be, that could be done manually. We just need to enable escape hatches for that, and I feel a BaseQueryWrapper would be enough for that.
From RTK-query's perspective, it would just stay `pending`.

**Comment by tobybaratta** [comment]
> > For the headers, there also is the use case of needing "Location" or "Content-Location" (or if you have to deal with anything MSFT, 'operation-location') back, as well as the "retry-after" time to handle retries separately. I could see "Last-Modified" being useful as well.
> 
> The point about 'retry-after' is interesting. I think it's possible to put together a solution for that [with this PR](#196), but it wouldn't exactly play nicely with our `retry` util — although, I doubt that matters. Someone could inspect the headers and then could just `setTimeout(() => api.dispatch(endpoint.initiate(arg)), timeoutFromHeader)` in `onError`. Is that how you'd imagine this being used? The only strange thing about this would be that a query would be in an error state on RTK Query's end, but in reality, should have some state like 'is-pending-update' and would be lost to the library.

This PR definitely helps and enables this use case perfectly. I wasn't planning on using the built-in retry (though it'd be nice) but to just wrap the baseQuery. I don't see an actual app needing to know anything there - just that it's still pending; and even if it does then it'd just need to be part of the response to display some other UI while retrying (a la adding a secondary "this could take a while" if there's some sort of really heavy traffic), which is no biggie. Thank you for this! I don't know if it resolves this for @LuukvH (though their above comment seems like it would), but it does for me.

**Comment by gfortaine** [comment]
@msutkowski We have also had this use case (to consume a custom X-total-count header, number of elements for pagination purposes). However, we have circumvented this limitation through a custom responseHandler + transformResponse :

```js
export const responseHandler = async (response): Promise<any> => {
  const data = await response.json();
  const headers = response.headers;

  return {
    data,
    headers
  };
};

export const transformResponse = async ({ data, headers }): Promise<any> => {
  const count = parseInt(headers.get('X-total-count'), 10);

  if (!Number.isNaN(count)) {
    return {
      count,
      searchResults: data
    };
  }

  return data;
};
