### ISSUE TITLE
Examples of "initiate" with react-redux connect

### ISSUE THREAD

**Issue by LouizFC** [rtk-incubator/rtk-query#198]
Greetings.

I have the following pattern inside my app:
```tsx
export const StorageConnectedView = connect(
  (state: MainState): StorageViewData => {
    const apiState = api.endpoints.getStorages.select()(state);

    const { data: storages = [] } = apiState;
    const status = extractStatus(apiState);

    const { selectedStorage } = getStorageViewState(state);
    return { status, storages, selectedStorage };
  },
  (dispatch: MainDispatch): StorageViewActions => ({
    onStorageCreation(storage) {
      dispatch(api.endpoints.createStorage.initiate(storage));
    },
    onStorageRefresh() {
      const { refetch } = dispatch(api.endpoints.getStorages.initiate());
      refetch();
    },
    onStorageClick(storage) {
      dispatch(selectStorage(storage));
    },
  })
)(StorageView);
```
[Here](https://rtk-query-docs.netlify.app/api/createApi#initiate) the docs says the following:

>When dispatching an action creator, you're responsible for storing a reference to the promise it returns in the event that you want to update that specific subscription. Also, you have to manually unsubscribe once your component unmounts. To get an idea of what that entails, see the Svelte Example or the React Class Components Example

I took a look at the `React Class Component Example` and found a similar pattern [here](https://codesandbox.io/s/react-class-component-example-48hyq?from-embed=&file=/src/features/posts/PostDetail.tsx:2027-2066) but I fail to see the "unsubscription" as pointed by out at the docs.

Am I using `refetch`correctly? or do I need to keep the `Promise` returned by `dispatch` somewhere? is it possible to make a simple redux-react connect example like [select](https://rtk-query-docs.netlify.app/api/createApi#select) has? 

Thanks in advance, this library is truly a blessing.

Edit: Forgot to mention, the code works as intended, I am just afraid that I might be misusing the lib in some way, like subscribing again on each refresh/creation without unsubscribing (leaking resources)

**Comment by phryneas** [comment]
Yeah, essentially it would be more complete like this:
```ts

  currentPromise?: ReturnType<ReturnType<typeof endpoints['getPost']['initiate']>>;

  componentDidMount() {
    const { id, getPost } = this.props;
    this.currentPromise = getPost(id);
  }

  componentDidUpdate(prevProps: PostDetailProps) {
    const { id, getPost } = this.props;
    if (id !== prevProps.id) {
      this.currentPromise?.unsubscribe()
      getPost(id);
    }
  }

  componentWillUnmount(){
    this.currentPromise?.unsubscribe()
  }
```

**Comment by LouizFC** [comment]
Perfect. Thank you very much @phryneas .

One last question: So, because these promises have a kind of "lifecycle" (initiate, use, unsubscribe, replace) they cannot be used inside a `connect` function, as in "plug and play", without further modifying the "Inner" component, right?

The code base I have has a lot of `connect`ed components, but the "Inner" components themselves are reusable `FunctionComponent`s.

I am not against rewriting this "connect logic" where it fits, but before I do that I wanted to know if there is some alternative or pattern I could use.

**Comment by LouizFC** [comment]
I am closing this. 

The better approach that I found is wrapping a connected component in a component that uses hooks or just not using a connected component. Anything other than that is possibly over engineering or edge cases.

My point on the codesandboxes is mentioned at https://github.com/rtk-incubator/rtk-query/issues/175#issuecomment-803011183

Thanks for the help

**Comment by phryneas** [comment]
Yeah, or using something like https://www.npmjs.com/package/hook2hoc :)

Exposing the actions is super useful for use in other frameworks, but it's more to build abstractions on top than to really "day to day" use it by hand.
