### ISSUE TITLE
`skipSelector` is not exported

### ISSUE THREAD

**Issue by markerikson** [rtk-incubator/rtk-query#211]
The functions in `buildSelector.ts` check if `queryArgs === skipSelector`, but we don't export it anywhere. We do _use_ `skipSelector` over in `buildHooks.ts`, but as of right now no one else can use that.

We need to export `skipSelector`.

**Comment by phryneas** [comment]
Hmm, the intention was really to just use that internally, to enable a `skip` behavior with the hooks. I don't really see a use case outside of hooks for that, but I might be wrong.

@SaulMoro - you've given that a :tada: - do you have a use case for that?

**Comment by SaulMoro** [comment]
In the build-hooks logic I have had to implement the skipSelector operation differently, to achieve the same behavior as https://github.com/rtk-incubator/rtk-query/blob/next/src/core/buildSelectors.ts#L98

**Comment by phryneas** [comment]
This is done by now.
