### ISSUE TITLE
TypeError getting `isFetching` from `use*Query` when `selectFromResult` is used.

### ISSUE THREAD

**Issue by StefanBRas** [rtk-incubator/rtk-query#219]
I wanted to use `selectFromResult` but found that to have `isSuccess` and the likes, they would also have to be passed through this selector. 

However this does not work for isFetching, and gives the error:
```
Property 'isFetching' does not exist on type '({ status: QueryStatus.uninitialized; originalArgs?: undefined; data?: undefined; error?: undefined; requestId?: undefined; endpointName?: string | undefined; startedTimeStamp?: undefined; fulfilledTimeStamp?: undefined; } & { ...; }) | ({ ...; } & { ...; }) | ({ ...; } & { ...; }) | ({ ...; } & { ...; })'.ts(2339)
```

Am i missing something with how this is to be used, or is it a bug?

For example this will work:
```typescript
const { data, isSuccess } = useGetPokemonByNameQuery(name, {
    selectFromResult: ({ data, isSuccess }) => ({ data, isSuccess })
  });
```
This will give a a type error:
```typescript
const { data, isFetching } = useGetPokemonByNameQuery(name, {
    selectFromResult: ({ data, isFetching }) => ({ data, isFetching })
  });
```

Here's a codesandbox to show it: 
https://codesandbox.io/s/concepts-queries-deduping-caching-forked-b4u4z?file=/src/Pokemon.tsx

**Comment by phryneas** [comment]
`isFetching` is actually not a part of `currentState` and needs to be calculated on a per-hook-level, by calling `defaultQueryStateSelector`, passed in as third argument into that selector function.

So, correct code would be 
```ts
  const {
    data: selectFromResultWithIsFetching,
    isFetching
  } = useGetPokemonByNameQuery(name, {
    selectFromResult: (result, lastResult: {data: any, isFetching: boolean} | undefined, defaultSelector) => {
      const { data, isFetching } = defaultSelector(result, {...lastResult});
      return { data, isFetching }
    }
  });
```

We clearly need to document this.
Also, this uncovered a bug in the types - this should also be possible to do as just
```diff
  const {
    data: selectFromResultWithIsFetching,
    isFetching
  } = useGetPokemonByNameQuery(name, {
-    selectFromResult: (result, lastResult: {data: any, isFetching: boolean} | undefined, defaultSelector) => {
+    selectFromResult: (result, lastResult, defaultSelector) => {
-      const { data, isFetching } = defaultSelector(result, {...lastResult});
+      const { data, isFetching } = defaultSelector(result, lastResult);
      return { data, isFetching }
    }
  });
```
which it currently isn't.
So we probably need changes like
```diff
export type QueryStateSelector<R, D extends QueryDefinition<any, any, any, any>> = (
  state: QueryResultSelectorResult<D>,
-  lastResult: R | undefined,
+  lastResult: NoInfer<R> | undefined,
  defaultQueryStateSelector: DefaultQueryStateSelector<D>
) => R;

export type DefaultQueryStateSelector<D extends QueryDefinition<any, any, any, any>> = (
  state: QueryResultSelectorResult<D>,
-  lastResult: Pick<UseQueryStateDefaultResult<D>, 'data'>
+  lastResult: Pick<UseQueryStateDefaultResult<D>, 'data'> | undefined
) => UseQueryStateDefaultResult<D>;
```
for this to be used better in the next version.

**Comment by StefanBRas** [comment]
Thanks for the throughout answer!

Regarding documentation, i at first only looked at the [selecing data from a query result](https://rtk-query-docs.netlify.app/concepts/queries#selecting-data-from-a-query-result) section, which made it seem like it just takes the data and filters it. Now from looking at the [useQuery api reference](https://rtk-query-docs.netlify.app/api/created-api/hooks#usequery) i see that `selectFromResult` takes a `QueryStateSelector` which isn't mentioned anywhere in the docs.

Hope this isn't comming of as complaning - I just wanted to add how I as a new user of RTK-query read the documentation.

And just to confirm - in the case where I want to select a subset of a query and get `IsFetching` in a component, your  first code block would be the correct way to do it?

**Comment by phryneas** [comment]
Yeah, there is still a lot of stuff to be documented and some edges are also only found by early adopters such as you :)

> And just to confirm - in the case where I want to select a subset of a query and get IsFetching in a component, your first code block would be the correct way to do it?

Yes (the same for `isLoading`) with one caveat: if your subset would be `undefined` at times, while `result.data` would be present, actually both `isLoading` and `isFetching` might both return to `true` where it would not be if you returned `result.data`.

Might need to think more about that. Maybe we can do that better in the next release.

**Comment by phryneas** [comment]
This should get handled better after we get https://github.com/reduxjs/redux-toolkit/pull/1035 in

**Comment by phryneas** [comment]
Closing this here.
