### ISSUE TITLE
How to use endpoints with promises, without a baseQuery? 

### ISSUE THREAD

**Issue by aarjithn** [rtk-incubator/rtk-query#221]
Hi there,

We have a js sdk that exposes set of methods, when called returns a promise. In `react-query`, it would be used as
`const { isLoading, error, data } = useQuery('repoData', sdk.fetchRepoData)`
where say fetchRepoData is the method name.

However, rtk query expects a function returning string/object that is then passed to what is defined as baseQuery.

From documentation:

> query is the only required property, and can be a function that returns either a string or an object which is passed to your baseQuery. If you are using fetchBaseQuery, this can return either a string or an object of properties in FetchArgs. If you use your own custom baseQuery, you can customize this behavior to your liking

I'm not sure what should be the baseQuery in this usecase. 
Is there a way to skip baseQuery by itself, and just define the methods directly in endpoints?

**Comment by msutkowski** [comment]
You would use a `queryFn` in this instance. You can see a usage example in the tests: https://github.com/rtk-incubator/rtk-query/blob/main/test/queryFn.test.tsx#L274. Additionally, you can also import and use `fakeBaseQuery` assuming you'd just be wrapping the external sdk and not have any other endpoints that would need baseQuery.

**Comment by aarjithn** [comment]
Great, thanks for the quick reply! 

I did see a mention to `queryFn` in 
https://rtk-query-docs.netlify.app/api/createApi#basequery

> The base query used by each endpoint if no `queryFn` option is specified. RTK Query exports a utility called fetchBaseQuery as a lightweight wrapper around `fetch` for common use-cases.

but couldn't see details of it anywhere in documentation. Would be good to add an example on how to use it.

**Comment by msutkowski** [comment]
> Great, thanks for the quick reply!
> 
> I did see a mention to `queryFn` in
> https://rtk-query-docs.netlify.app/api/createApi#basequery
> 
> > The base query used by each endpoint if no `queryFn` option is specified. RTK Query exports a utility called fetchBaseQuery as a lightweight wrapper around `fetch` for common use-cases.
> 
> but couldn't see details of it anywhere in documentation. Would be good to add an example on how to use it.

Yea - we still have a handful of things to document from the last release, and this is definitely on the list!
