### ISSUE TITLE
Ensure onSuccess is called with transformed data when tranformResponse is used

### ISSUE THREAD

**Issue by asherccohen** [rtk-incubator/rtk-query#222]
Following the conversation with @phryneas on the discord channel ([link](https://discord.com/channels/102860784329052160/103538784460615680/835129866789060638) ), we noticed that the flow of responses in callback methods with a transformResponse does not guarantee the same shape of data, this requires to transform in each callback (potential bottleneck and error prone).

I don't have the time for a PR, so here's the steps to get there.

How to reproduce:
- create a service
- add a transformResponse callback (with a simple fn that changes the shape of response)
- add an onSuccess callback and log "result". 

Expected:
"result" should be transformed

What happens:
"result" is not transformed

Code:
https://github.com/rtk-incubator/rtk-query/blob/c769479a056f4ddf0972ae9bff19a2ca4352751f/src/core/buildThunks.ts#L235-L241

The above lines of code demonstrate that onSuccess and onError are called with the original data.

> It's a bit unexpected that onSuccess and onError are called before the data is persisted in the store
> Could be moved out of the asyncThunk into initiate.

**Comment by phryneas** [comment]
Might actually make sense to tackle this together with #215 and move all lifecycle event handling into one central place in the middleware.

**Comment by asherccohen** [comment]
EDIT: Check that also selectFromResult adheres to the same shape.

**Comment by phryneas** [comment]
@asherccohen it should, that one reads from the redux store wayyy later

**Comment by phryneas** [comment]
This is on the integration branch right now, closing it here.
