### ISSUE TITLE
Mutation does not invalidate

### ISSUE THREAD

**Issue by sumeyradavran** [rtk-incubator/rtk-query#226]
Hello 👋  I want to say great job for all you did. I am closely following updates and I am planning on moving to rtk-query.

I am playing around and I think I need some help regarding invalidation. Here is a codesandbox link and I am trying to invalidate the query and refetch getAll endpoint. 
This is the basic mechanism I followed on my project and it is not working in the project also. https://codesandbox.io/s/crazy-ives-y4wtz?file=/src/pokemonApi.ts

**Comment by phryneas** [comment]
Thanks for the report. It looks like you are doing everything right from your side - we'll look into it!

**Comment by phryneas** [comment]
Okay, I am sorry, I was completely blind here and missed the obvious. You forgot to add the middleware.

```diff
  configureStore({
    reducer: {
      [pokemonApi.reducerPath]: pokemonApi.reducer
    },
+    middleware: getDefaultMiddleware => getDefaultMiddleware().concat(pokemonApi.middleware)
  });
```
