### ISSUE TITLE
CORS refetching

### ISSUE THREAD

**Issue by vaqif14** [rtk-incubator/rtk-query#227]
Thanks for the great lib.  I have a CORS problem ( this is a backend problem) but when I get this error query is refetching every time nonstop.

**Comment by phryneas** [comment]
This is not enough info for us to really do anything with it. 

Screenshots of errors or the network tab in the devtools, the parts of code where you call something... we need info.

**Comment by vaqif14** [comment]
I customly created cors error to show
[The full log file ](https://github.com/rtk-incubator/rtk-query/files/6439856/localhost-1620372581227.log)

**Comment by phryneas** [comment]
So, basically: a CORS error is never caused by RTK Query, but either by you missing some headers or by a wrong server config.
If it works with `fetch`, it works with `fetchBaseQuery`, if it doesn't work in `fetchBaseQuery`, it will not work in `fetch`.

What irritates me is actually that it retries it so often. But I do not know anything about your code to analyze that.
My theory is that due to some reason your component unmounts and remounts - but at this point I don't even know if you are dispatching `invoke` by hand or using React and the `useQuery` hook.

Please show some code, in the best case a reproduction in a codesandbox.

**Comment by vaqif14** [comment]
```js
import { createApi } from '@reduxjs/toolkit/query/react';
import { fetchBaseQuery } from '@reduxjs/toolkit/query';
import { MAIN_URL } from './constants/defaultValues';

export const api = createApi({
  baseQuery: fetchBaseQuery({ baseUrl: MAIN_URL }),
  entityTypes: [],
  endpoints: build => ({
    getTaxpayers: build.query<GetTaxpayersApiResponse, GetTaxpayersApiArg>({
      query: queryArg => ({
        url: `/v1/public/taxpayer`,
        method: 'POST',
        body: queryArg.taxpayerFilterWebDto,
      }),
    }),
    getTaxpayerBasicInfo: build.query<GetTaxpayerBasicInfoApiResponse, GetTaxpayerBasicInfoApiArg>({
      query: queryArg => ({
        url: `/v1/public/taxpayer/basic-info/${queryArg.searchTerm}`,
      }),
    }),
    getTaxpayerBasicInfoTw: build.mutation<
      GetTaxpayerBasicInfoApiResponse,
      GetTaxpayerBasicInfoApiArg
    >({
      query: queryArg => ({
        url: `/v1/public/taxpayer/basic-info/${queryArg.searchTerm}`,
      }),
    }),
  }),
});

export type GetTaxpayersApiResponse = /** status 200 OK */ TaxpayerWebDto[];
export type GetTaxpayersApiArg = {
  taxpayerFilterWebDto: TaxpayerFilterWebDto;
};
export type TaxpayerWebDto = {
  id?: string;
  tin?: string;
  name?: string;
  registrationDate?: string;
  taxpayerType?: 'INDIVIDUAL' | 'LEGAL_ENTITY';
  taxpayerStatus?: 'ACTIVE' | 'STOPPED' | 'ENDED';
  vatRegistrationDate?: string;
  director?: string;
};
export type TaxpayerFilterWebDto = {
  tinOrFin?: string[];
  taxpayerTypes?: ('INDIVIDUAL' | 'LEGAL_ENTITY')[];
  taxpayerStatuses?: ('ACTIVE' | 'STOPPED' | 'ENDED')[];
  registrationPeriodStart?: string;
  registrationPeriodEnd?: string;
  outstandingPaymentToBudgetMin?: number;
  outstandingPaymentToBudgetMax?: number;
  objectCode?: string;
  vatRegistrationPeriodStart?: string;
  vatRegistrationPeriodEnd?: string;
  activityTypes?: string[];
  familyFarmEnum?: 'YES' | 'NO';
  landOwner?: 'YES' | 'NO';
  cashInconsistencies?: 'YES' | 'NO';
  fineDebtAmountMin?: number;
  fineDebtAmountMax?: number;
  overpaymentAmountMin?: number;
  overpaymentAmountMax?: number;
  foundations?: string[];
  offset?: number;
  fetchCount?: number;
};

export type GetTaxpayerBasicInfoApiResponse = /** status 200 OK */ TaxpayerBasicInfoWebDto[];
export type GetTaxpayerBasicInfoApiArg = {
  searchTerm: string;
};
export type TaxpayerBasicInfoWebDto = {
  tin?: string;
  fin?: string;
  name?: string;
};
```

**Comment by vaqif14** [comment]
> ```js
> import { createApi } from '@reduxjs/toolkit/query/react';
> import { fetchBaseQuery } from '@reduxjs/toolkit/query';
> import { MAIN_URL } from './constants/defaultValues';
> 
> export const api = createApi({
>   baseQuery: fetchBaseQuery({ baseUrl: MAIN_URL }),
>   entityTypes: [],
>   endpoints: build => ({
>     getTaxpayers: build.query<GetTaxpayersApiResponse, GetTaxpayersApiArg>({
>       query: queryArg => ({
>         url: `/v1/public/taxpayer`,
>         method: 'POST',
>         body: queryArg.taxpayerFilterWebDto,
>       }),
>     }),
>     getTaxpayerBasicInfo: build.query<GetTaxpayerBasicInfoApiResponse, GetTaxpayerBasicInfoApiArg>({
>       query: queryArg => ({
>         url: `/v1/public/taxpayer/basic-info/${queryArg.searchTerm}`,
>       }),
>     }),
>     getTaxpayerBasicInfoTw: build.mutation<
>       GetTaxpayerBasicInfoApiResponse,
>       GetTaxpayerBasicInfoApiArg
>     >({
>       query: queryArg => ({
>         url: `/v1/public/taxpayer/basic-info/${queryArg.searchTerm}`,
>       }),
>     }),
>   }),
> });
> 
> export type GetTaxpayersApiResponse = /** status 200 OK */ TaxpayerWebDto[];
> export type GetTaxpayersApiArg = {
>   taxpayerFilterWebDto: TaxpayerFilterWebDto;
> };
> export type TaxpayerWebDto = {
>   id?: string;
>   tin?: string;
>   name?: string;
>   registrationDate?: string;
>   taxpayerType?: 'INDIVIDUAL' | 'LEGAL_ENTITY';
>   taxpayerStatus?: 'ACTIVE' | 'STOPPED' | 'ENDED';
>   vatRegistrationDate?: string;
>   director?: string;
> };
> export type TaxpayerFilterWebDto = {
>   tinOrFin?: string[];
>   taxpayerTypes?: ('INDIVIDUAL' | 'LEGAL_ENTITY')[];
>   taxpayerStatuses?: ('ACTIVE' | 'STOPPED' | 'ENDED')[];
>   registrationPeriodStart?: string;
>   registrationPeriodEnd?: string;
>   outstandingPaymentToBudgetMin?: number;
>   outstandingPaymentToBudgetMax?: number;
>   objectCode?: string;
>   vatRegistrationPeriodStart?: string;
>   vatRegistrationPeriodEnd?: string;
>   activityTypes?: string[];
>   familyFarmEnum?: 'YES' | 'NO';
>   landOwner?: 'YES' | 'NO';
>   cashInconsistencies?: 'YES' | 'NO';
>   fineDebtAmountMin?: number;
>   fineDebtAmountMax?: number;
>   overpaymentAmountMin?: number;
>   overpaymentAmountMax?: number;
>   foundations?: string[];
>   offset?: number;
>   fetchCount?: number;
> };
> 
> export type GetTaxpayerBasicInfoApiResponse = /** status 200 OK */ TaxpayerBasicInfoWebDto[];
> export type GetTaxpayerBasicInfoApiArg = {
>   searchTerm: string;
> };
> export type TaxpayerBasicInfoWebDto = {
>   tin?: string;
>   fin?: string;
>   name?: string;
> };
> ```

Code Generated by `rtk-query-codegen`

**Comment by phryneas** [comment]
If your MAIN_URL is on another host than your script, you probably need to add `mode: 'cors'` :
```js
+  baseQuery: fetchBaseQuery({ baseUrl: MAIN_URL }),
-  baseQuery: fetchBaseQuery({ baseUrl: MAIN_URL, mode: 'cors' }),
```

AND the server has to be configured to accept CORS requests.

You can read up more on CORS on https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

As for why is is rerunning so often, that is a completely unrelated problem:

You pass in a very nested object into your query and you have to keep the reference for that stable since it changes on every render to a new object (== new request) otherwise:

```js
  const stableArg = useMemo(() => ({
    taxpayerFilterWebDto: { fetchCount: 1000 },
  }, [])
  const { data, isLoading } = api.useGetTaxpayersQuery(stableArg);
```
