### ISSUE TITLE
Understanding GraphQL Support

### ISSUE THREAD

**Issue by a-laughlin** [rtk-incubator/rtk-query#228]
I may be able to contribute, so want to understand the state of things first.

The [React with GraphQL example](https://rtk-query-docs.netlify.app/examples/react-with-graphql), contains an example of rtk-query with GraphQL queries.

The [comparison page](https://rtk-query-docs.netlify.app/introduction/comparison) contains this image:
![image](https://user-images.githubusercontent.com/1176527/116791945-e8005500-aa7a-11eb-9934-4054b1fb8f1d.png)

Does that difference imply rtk-query does not officially support GraphQL?

If so:
- Any interest in officially supporting GraphQL?
- Existing opinions on the shape of ideal GraphQL support?
- What are the gaps between ideal and current GraphQL support?  e.g., Mutations?  Subscriptions? (#186)  Normalized cache?

**Comment by phryneas** [comment]
RTK-Q is a request cache, but completely independent of the transport protocol and data that is being transported.
The goal is explicitly to have a "per request" cache and not a normalized cache. So it can be used for GraphQL, but not have all the benefits clients explicitly written for GraphQL have. So it's probably around the level of `urql` with their [Document Caching](https://formidable.com/open-source/urql/docs/basics/document-caching/), but will never go beyond that.
And that's okay, after all, there are specialized tools there for a reason and this would become a monster if it would do everything perfectly.

As for subscriptions, I have opened [a Pull Request](https://github.com/reduxjs/redux-toolkit/pull/1034) against the new codebase that would enable that more comfortably.

It's essentially this API:
https://github.com/rtk-incubator/rtk-query/blob/cdc1cacca6cd42a7b2bdd12c66540ac11c7d5d33/test/lifecycle.test.tsx#L76-L99

(You can scroll down further in that file to see that in combination with `entityAdapter`.

So with that, all building blocks are in place, our "graphql support" is as good (imho, with those lifecycles, better) than React-Query who "officially support" GraphQL, but I would not feel comfortable to really advertise it.  
There are better tools and you would usually go for those except if you have the need to very tightly integrate with Redux, or if you already use RTK and don't need all the fancy extra stuff from Apollo.

That said, the next thing that would be great to add would be a plugin for `graphql-codegen`. We have [something similar for OpenAPI](https://github.com/rtk-incubator/rtk-query-codegen) so it would probably make sense to integrate that somehow over there - maybe transforming that whole repo there into a monorepo for all kinds of codegens.

**Comment by a-laughlin** [comment]
Thanks for the quick response and explanation @phryneas.  Nice test examples.

Regarding `graphql-codegen`, the concept is to generate something like [generated.ts](https://github.com/rtk-incubator/rtk-query-codegen/blob/next/test/fixtures/generated.ts) from a GraphQL schema?

**Comment by phryneas** [comment]
Yes, but not from a full schema, but from queries and mutations in your codebase.

With `graphql-codegen`, you usually put some `.graphql` files (or `.js/ts` files with graphql-tag usage) into your codebase and it generates one central file with hooks for apollo or whatever plugin you use out of all those

**Comment by a-laughlin** [comment]
I'm comparing state management options with new business needs this week.  Adding RTK-query to the list to evaluate, along with the need for schema codegen.  Should be able to estimate how much time I can commit afterward.

**Comment by phryneas** [comment]
The next release of Redux Toolkit will have support for [streaming updates](https://deploy-preview-1016--redux-starter-kit-docs.netlify.app/usage/rtk-query/streaming-updates) which should cover subscriptions.

All further feature requests should be filed over at https://github.com/reduxjs/redux-toolkit/ - I'm closing this here now
