### ISSUE TITLE
Access raw endpoint promise method

### ISSUE THREAD

**Issue by mtodberg** [rtk-incubator/rtk-query#230]
I'm in the process of investigating if rtk-q fits into our large scale application. We are already using redux-toolkit and redux-saga. The sagas are for complicated async logic, in which we sometimes execute regular api requests. With rtk-q consolidating the endpoints in a single abstract structure, how can I perform the raw ajax request in a saga with something that returns a promise? Afaik, there are only the generated hooks and the thunk actioncreator way (`initiate`)?

I want to do something like this in a saga:
```ts
const response = yield put(???); // Takes in a function that returns a promise.
```

**Comment by phryneas** [comment]
Yielding the `initiate` thunk will return a Promise (even `put`ing it in saga should do that), but keep in mind that that promise just returns the state after the query, no information if that query actually ran.
RTK-Q might decide that there is already a request in flight or that the state is just not stale (this can be skipped by `forceRefetch: true`) and return immediately.

**Comment by mtodberg** [comment]
So in other words there are no way to bypass the rtk-q mechanisms? I noticed that I could do the following, but it's too much of a hack for me:

```ts
const response = yield put(fooApi.endpoints.foo.initiate(payload) as any); <-- has to be cast to any as `put` doesn't accept thunks
const result = yield response; <-- returns raw api response
```

**Comment by phryneas** [comment]
> So in other words there are no way to bypass the rtk-q mechanisms?

Is your question right now "there is no way to use this while skipping over it's complete implementation?"?


Generally:

If `put` does not accept thunks, you have to type it accordingly to be aware of your middleware - just as you need to type `dispatch` accordingly to be aware of the thunk middleware.
Apart from the `as any`, this is not a hack.

But I have to reiterate: Your code might return before the query has run for the first time, if you trigger it a second time while the exact same query with the same arguments is already running.

Better would probably to wait for the next completed a completion, so
```js
// initiate query
const response = yield put(fooApi.endpoints.foo.initiate(payload)) 
// wait for finish
yield take(api.endpoints.foo.isFulfilled(payload))
// get result
const result = yield select(api.endpoints.foo.select(payload)) 
```

**Comment by mtodberg** [comment]
Thank you for the code example. That cleared things up quite a bit. Although, I don't see how you would correctly type `put/dispatch` with `redux-toolkit` and `redux-toolkit-query` as I'd somehow have to extract all the action types from `createActions` and `createApi`'s underlying thunks. Is that something you have considered?

**Comment by mtodberg** [comment]
Your code example clears things up for me, thanks!

**Comment by mtodberg** [comment]
@phryneas FYI, created an [issue](https://github.com/reduxjs/redux-toolkit/issues/1037) in the `redux-toolkit` repository as this basically another, yet highly related question when typing redux-saga's `put` effect.

**Comment by mtodberg** [comment]
@phryneas Seems like there is no `api.endpoints.foo.isFulfilled`. How do you wait for the ongoing request to finish?

**Comment by mtodberg** [comment]
Like this maybe?
 
```ts
// initiate query and wait for finish 
yield yield put(fooApi.endpoints.foo.initiate(payload), { forceRefetch: true });
// get the result
const result = yield select(api.endpoints.foo.select(payload)) 
```

**Comment by phryneas** [comment]
As I said, waiting for the returned promise will under some circumstances return before the fetch has finished. This API is not designed to be used in an imperative way.

**Comment by phryneas** [comment]
It is meant for declarative consumption. It will at all times give you consistent data, but the timing should not be of your concern.

But to answer your question above, it is `matchFulfilled`. See Docs: https://deploy-preview-1016--redux-starter-kit-docs.netlify.app/api/rtk-query/created-api/endpoints#matchers
