### ISSUE TITLE
Help: Is the tag system intended to replace an entity adapter?

### ISSUE THREAD

**Issue by garrettjoecox** [rtk-incubator/rtk-query#231]
Hi there, we're trying to understand how RTKQ fits into our application, and when to use our traditional RTK (slices/thunks/entityAdapters) setup vs using RTKQ. I took the posts example from your documentation and fleshed it out a bit further for experimentation and made the following observations:

```ts
// THIS IS PSEUDO-CODE
function App() {
  const [activePostId, setActivePostId] = useState(null);

  return (
    <>
      <CreatePost />
      <PostsList onPostSelect={setActivePostId} />
      {activePostId && <PostDetail id={activePostId} />}
    </>
  );
}

function PostsList({ onPostSelect }) {
  const { data: posts } = useListPostsQuery();

  return (
    <>
      {posts.map((post) => (
        <PostItem id={post.id} onClick={() => onPostSelect(post.id)} />
      ))}
    </>
  );
}

function PostItem({ id }) {
  const { data: post } = useGetPostQuery(id);

  // Display post summary
}

function PostDetail({ id }) {
  const { data: post } = useGetPostQuery(id);
  const [updatePost] = useUpdatePostMutation();

  // Display post details & allow updating
}

function CreatePost() {
  const [createPost] = useCreatePostMutation();
  // create post
}
```

- On app mount a single 'listPosts' request would fire off, then when done, n(n = number of posts) 'getPost' requests would fire off. 
- If I then create a new post, only the 'listPosts' call is invalidated, so that will refetch, the rest (n 'getPost' calls) will not, since they are unrelated.
- If I then update a post, the 'listPosts' call and a single 'getPost' call are invalidated, and will both refetch, the rest of unrelated 'getPost' calls will not.

While this handles some cases, it is still not quite optimal for our use case(due to how our API is set up), there are a number of unnecessary calls still being made here that we could reduce if using an entity adapter over the RTKQ tags:
- On mount, the 'listPosts' call gets all the information the PostItems need, meaning they are making unnecessary 'getPost' calls.
- On post creation, the newly created post is returned from the API, meaning we can just add it to the posts entity adapter client side, and not bother fetching all posts again.
- Similar to above, the updated post is returned from the API, meaning you can just augment the single post in the entity adapter, rather than firing off the two(listPosts and getPost) additional requests.

Just wanted to get some feedback on if my understanding is correct, and if I should be using the entity adapters instead  for this `posts` example.

**Comment by phryneas** [comment]
The tag system (and RTK-Q, generally) is intended for cases where you have no problem with making a few more requests if it saves you the work of writing normalization by hand.

Generally, RTK-Q is a non-normalized cache. The tag system solves the problem of keeping the data in there up-to-date - at the cost of making a few more requests. Of course you could do this by using optimistic updates instead, but that would get quite a lot of code fast and undo the real benefit (little code) you gain from RTK-Q.

That doesn't mean that you have to make as excessively many requests as you showed up there.

As for your components up there, I would design it a bit differently:

`PostItem` would not call `useGetPostQuery`, but either get the `item` passed in directly as a prop, or use `useQueryState` in combination with `selectFromResult` to select it's value from the `useListPostsQuery` endpoint result. (The latter would allow you to use `React.memo` on `PostItem` if actually necessary.)

That way, only your `PostsList` and your `PostDetail` would make queries. So you went down from `n+2` queries down to 2.

**Comment by phryneas** [comment]
I'm closing everything here now. If there's any need for further discussion, that should take place in a new issue over at https://github.com/reduxjs/redux-toolkit/
