### ISSUE TITLE
Mutation fetch when component mount

### ISSUE THREAD

**Issue by vaqif14** [rtk-incubator/rtk-query#236]
Is it possible to get data for the first time when the page mount in mutation? (without call with useEffect)

**Comment by phryneas** [comment]
Mutations are not there for getting data, but for telling the server to change something in the database, like sending a form.
It is not really a standard use case to change data on the server every time a site loads, without user interaction, so no, that is not really something we support.

What do you want to do there?

**Comment by vaqif14** [comment]
> Mutations are not there for getting data, but for telling the server to change something in the database, like sending a form.
> It is not really a standard use case to change data on the server every time a site loads, without user interaction, so no, that is not really something we support.
> 
> What do you want to do there?

Ok, thanks for the reply. I have a table that firstly fetching 1000 data after change page it sends a post request to fetch other new table data. For starting I  don't want to use useEffect for clean code 🤪  but no problem

**Comment by phryneas** [comment]
If this is only fetching data, it should be a query, not a mutation. Doesn't matter if it's a POST or not.

**Comment by vaqif14** [comment]
How I can request when the button clicked in a query?

**Comment by phryneas** [comment]
For pagination purposes, [see the pagination example in the docs](https://rtk-query-docs.netlify.app/concepts/pagination#trigger-the-next-page-by-incrementing-the-page-state-variable)
