### ISSUE TITLE
Manual queryKey specification

### ISSUE THREAD

**Issue by msutkowski** [rtk-incubator/rtk-query#30]
We talked briefly about this on Discord, but I believe we may want to allow for folks to eventually specify a manual `queryKey` and bypass our default method. We do this with `defaultSerializeQueryArgs` currently and could unlock the same ability at the individual query level.

@phryneas thoughts?

**Comment by phryneas** [comment]
Yes, the combination of per-query key calulation specification and [transformResponse](https://github.com/rtk-incubator/rtk-query/issues/31) would also allow for endless scrolling in the style of [apollo](https://www.apollographql.com/docs/react/caching/cache-field-behavior/#handling-pagination).

Only question would be: do we generally leave calculation of the full queryKey to the user or should we always prefix it with `endpoint` to prevent accidental collisions?

**Comment by msutkowski** [comment]
Perhaps both? Handle the default as prefixing, but allow them to bypass it if desired?

**Comment by phryneas** [comment]
I assume that would make up for a very complicated api as we can't just take a string return value for both cases

**Comment by msutkowski** [comment]
In that case, maybe it's best to let users have full control here as they're already reaching for an escape hatch?

**Comment by phryneas** [comment]
Hmm, true.

**Comment by phryneas** [comment]
I'm closing everything here now. If there's any need for further discussion, that should take place in a new issue over at https://github.com/reduxjs/redux-toolkit/
