### ISSUE TITLE
Advanced invalidation/revalidation

### ISSUE THREAD

**Issue by msutkowski** [rtk-incubator/rtk-query#37]
Requires additional discussion for usage.

- [ ] invalidateOnMount: add to `useQuery` add option with `maximumAge`?
- [ ] invalidateOnReconnect & invalidateOnReconnect either add as per-api option, or just expose action to trigger this globally?

**Comment by phryneas** [comment]
I'm closing everything here now. If there's any need for further discussion, that should take place in a new issue over at https://github.com/reduxjs/redux-toolkit/
