### ISSUE TITLE
Detailed documentation updates

### ISSUE THREAD

**Issue by msutkowski** [rtk-incubator/rtk-query#40]
- [ ] Explain request cancellation behavior in `useQuery` / abort controller / etc
- [x] Clearly explaining behavior of invalidation/provides and different possible scenarios - see https://github.com/rtk-incubator/rtk-query/pull/39#discussion_r525339990
- [x] Show `transformResponse` usage - currently in graphQL example
- [x] Add info about serialized values in the store, especially when using `transformResponse`
- [ ] Offline support documentation?
- [x] Auth
   - ~~[x] Local Storage~~ _(skipping due to bad practice, but a user can see where to do it from the token example)_
   - [ ] Cookies
   - [x] Token from store
- [ ] Do a small writeup focusing on existing redux users and how they can leverage this
   - [ ] Hooks encapsulation to emulate common redux selectors patterns
- [ ] Document timestamps `fulfilledTimestamp` and `startedTimeStamp`
- [x] More `baseQuery` details with examples
  - [x] Axios custom base query?

**Comment by phryneas** [comment]
I'm closing everything here now. If there's any need for further discussion, that should take place in a new issue over at https://github.com/reduxjs/redux-toolkit/
