### ISSUE TITLE
Enhancing Endpoint definitions.

### ISSUE THREAD

**Issue by phryneas** [rtk-incubator/rtk-query#52]
Just an idea: where `injectEndpoints` creates/overrides endpoints, it might be a good idea to have a `enhanceEndpoints` helper.

That helper would only allow to adjust existing endpoints, e.g. by adding `provides`/`invalidates`.

That way one file could contain a "generated from OpenAPI" api definition and you could chain a second file behind that, that would only add certain properties and do light adjustments - allowing for continuous re-creation of the generated file.

**Comment by phryneas** [comment]
I've contacted the maintainers of `oazapfts` as a possible client generator over at https://github.com/cellular/oazapfts/issues/41

**Comment by markerikson** [comment]
Oh hey, that looks interesting.

I tried out the official `openapi-generator` Axios+TS thing last year, and was _not_ impressed with its output.  5000+ lines of boilerplate TS for just a few endpoints.

**Comment by phryneas** [comment]
current progress of code generation: 
![image](https://user-images.githubusercontent.com/4282439/101289589-bb168180-37fd-11eb-9104-fcae4b52fa07.png)

https://github.com/phryneas/rtk-query-codegen-openapi/blob/main/src/generate.ts
If you want to play around with it:
requires this branch from 
https://github.com/phryneas/oazapfts/tree/expose-class
yalc it in & run the generate.ts with ts-node

**Comment by kahirokunn** [comment]
@phryneas It works for me ❤️ 
The code also uses the TypeScript API, which I thought was awesome! 👍

**Comment by kahirokunn** [comment]
@phryneas 

What is current progress?
Is there anything I can do to help? 👍  (eg. cli interface

**Comment by kahirokunn** [comment]
For the first stage, unoptimized code should be sufficient.

**Comment by phryneas** [comment]
Hey @kahirokunn,
I'm sick at the moment so I can only work on stuff for like one hour or so and have to rest then, so this has been quite delayed.
The actual state now produces actually working code - see https://github.com/phryneas/rtk-query-codegen-openapi/blob/main/test/generated.ts

If you could help out there, that would be great. I would try & do some work on the rtk-query side then.
Stuff currently outstanding:

* add a cli
* allow to specify some overrides for example for baseUrl
* generation of provides/invalidates is completely untouched now, so experimentation in that direction is very welcome

**Comment by kahirokunn** [comment]
@phryneas Oh, sorry 🙏 Take care 😢 

I first created a pull request for the first "add cli".
If this one works, I'll work on the second and third!

https://github.com/phryneas/rtk-query-codegen-openapi/pull/1

**Comment by kahirokunn** [comment]
I'm very excited about this project.
So I've included the following in the pull request!

* allow to specify some overrides for example for baseUrl

**Comment by kahirokunn** [comment]
This already works for me, but is there anything else that needs to be done to get the alpha version out?

**Comment by phryneas** [comment]
For it to be really useful, we'll need #102 and another alpha of rtk-query itself. Could probably be somewhere this weekend or early next week. I'll try to do both releases simultaneously then.

**Comment by phryneas** [comment]
Also, I have to get that PR in for oazapfts, although I can fork that temporarily if neccessary.

**Comment by kahirokunn** [comment]
I can't wait to get those pull-links merged and released!
If there's any additional work that needs to be done, anything at all, please let me know! I'll do my best to help!

**Comment by phryneas** [comment]
You could try out #102 a bit and give feedback if it works well. So far I think we could just merge that for now and iterate on it later, but some feedback would be great.

Also, we will still need a docs chapter about code generation (you can assume that the package will be published as @rtk-incubator/rtk-query-codegen-openapi for now) and the usage of the cli-generated code in combination with #102, if that's something you could see yourself working on.

**Comment by kahirokunn** [comment]
I commented on #102.
Looks pretty good to me :+1: 

I think it's better to wait for #102 to release the stable version, but I guess we don't have to wait for #102 for the alpha version.

> Also, we will still need a docs chapter about code generation

I don't know that I can do this well, but I'll give it a try.

By the way, it's easier to write the documentation itself after the alpha version is released to npm. 👀

**Comment by kahirokunn** [comment]
How about exporting all use* hooks option?

**Comment by kahirokunn** [comment]
I fixed some bugs. 👍 
https://github.com/rtk-incubator/rtk-query-codegen/pull/2
