### ISSUE TITLE
Improve "Comparison" page

### ISSUE THREAD

**Issue by markerikson** [rtk-incubator/rtk-query#77]
Per https://twitter.com/andrewingram/status/1333870894490464256:

> the docs include another now-familiar comparison table. There has to be a better way of meaningfully comparing alternative solutions in the same space, because comparison tables are fundamentally misleading.

what would make it better?

> Honestly, prose.  All tables do is highlight a one-way absence of a feature because you’ll always be biased towards focusing on things you specifically considered in your design choices. By nature they have to be flawed because otherwise you’ll just be constantly adding rows.

**Comment by msutkowski** [comment]
Hmmm. Regarding this, we have some various copy that explains the motivation throughout the docs, as well as now a collection of responses we could shape into this. I'll give it a shot tomorrow but will start compiling here as things come up.

> With RTK Query, you usually define your entire API definition in one place. This is most likely different from what you see with other libraries such as swr or react-query, and there are several reasons for that. Our perspective is that it's much easier to keep track of how requests, cache invalidation, and general app configuration behave when they're all in one central location in comparison to having X number of custom hooks in different files throughout your application.


> there are countless "lifecycle event" and other places to hook into where you can just access state and dispatch actions - for example for authentication purposes
> 
> your reducers can just listen to the internal actions of RTK query and adjust their state according to data that it is coming in
> 
> it's a bit a philosophical difference to React-Query. Where you define a lot of individual queries in React-Query, you define your API as one unit in RTK-Query. This feels very reduxy and allows you to define stuff like "when a mutation modifies an object, refetch all queries that returned that object" - either only by defining "entityTypes" for these queries & mutations or by going as far as specifying which exact entities are being returned. Also, the central definition makes sure you don't duplicate stuff and offers very good TypeScript support.
> 
> where React-Query only works in React, RTK-Query works everywhere Redux would work. For example, we have a Svelte Codesandbox. (edit by matt: partially true - I believe they're working on svelte / vue packages as well)

**Comment by markerikson** [comment]
Tanner Linsley suggests forking React-Query's comparison page and using that as a more detailed basis:

https://twitter.com/tannerlinsley/status/1333941616524939264

> Given the public/Twitter comparison to React Query and SWR, I would have forked (at least most of) the React Query comparison table as a starting point. From my perspective, the current version seems way too terse, possibly in an effort to appear on par with the others.

Link:

https://react-query.tanstack.com/docs/comparison

**Comment by markerikson** [comment]
There was an excellent "React Query vs RTK Query" Reddit thread at https://www.reddit.com/r/reactjs/comments/mggpr7/rtk_query_vs_react_query_which_to_use_in_what/ where all three of us chimed in and gave some good comparisons. We should copy that content over here.

**Comment by phryneas** [comment]
I'm closing everything here now. If there's any need for further discussion, that should take place in a new issue over at https://github.com/reduxjs/redux-toolkit/
