### ISSUE TITLE
Naming of hook option for refetch on mount/arg change.

### ISSUE THREAD

**Issue by phryneas** [rtk-incubator/rtk-query#85]
So, we have a functionality`in #80, but are missing a good name and are hoping for some feedback from the community.

Imagine these three use cases:

### basic/no option
```ts
// This will only fetch data if data for useGetPostsQuery({ page: 1 }) has not been fetched yet by this or another component.
// Similarly, changing `page` to `2`, it will only fetch data if no data is present yet.
const result = useGetPostsQuery({ page: 1 })
```

### always refresh/refetch
```ts
// This will fetch data on first mount and on every change of `page`
const result = useGetPostsQuery({ page: 1 }, { XXXXonYYYY: true })
```

### refresh/refetch if data is older than X seconds
```ts
// This will fetch data on first mount and change of `page`, but only if there is no data in the cache or if that data is older than 20 seconds.
const result = useGetPostsQuery({ page: 1 }, { XXXXonYYYY: 20 })
```

So, now the question is: What is a correct name for `XXXXonYYYY`?

`refetchOnMount` does not seem quite right, because this is also a `refetchOnArgChange`. `refetchOnMountOrArgChange` is horribly long, albeit very on-spot.

So far, we've come up with `refetchOnSubscribe`, `refetchOnUse`, `refetchOnQuery`, `refreshOnSubscribe`, `refreshOnUse` and `refreshOnQuery`, but we don't really have a strong preference on either of these.

So... maybe we can get some ideas or preferences from the community on this one?

**Comment by michaelaflores** [comment]
Is `refetchOnRender` accurate?

**Comment by adokce** [comment]
I understand that long names would usually drive people away from using the api, but `refetchOnMountOrArgChange` sounds beautiful (and perfectly descriptive) to me

**Comment by meesvandongen** [comment]
Simply "refetch" may be enough.

**Comment by phryneas** [comment]
> Is `refetchOnRender` accurate?

No, if you rerender 20 times, but the argument does not change, it will not even evaluate refetching. It's only mount & actual change of argument (an object as argument will be shallow-compared with the last render).

**Comment by Shrugsy** [comment]
> Is `refetchOnRender` accurate?

I would read that as re-fetching *every* render, including renders after the initial one when already fetched, as well as when args did not change (which would cause an infinite loop)

**Comment by phryneas** [comment]
> Simply "refetch" may be enough.

Interesting idea :)
We already have that as an active method returned from the hook, so that might be a bit confusing in the docs :thinking:

**Comment by meesvandongen** [comment]
> > Simply "refetch" may be enough.
> 
> Interesting idea :)
> We already have that as an active method returned from the hook, so that might be a bit confusing in the docs 🤔

Then we can make it refresh instead

**Comment by Shrugsy** [comment]
- `eagerRefetch` / `eagerRefresh`?

**Comment by meesvandongen** [comment]
autoRefetch

**Comment by asherccohen** [comment]
I don't see the need for stating "mount" as it's the default behavior, and it's clear it needs to mount to be able to run.

So we can find alternative definitions to describe a change:
refetchOnDiff
refetchOnDelta
refetchOnUpdate

Or simply we could see it from the point of view of data age:
refetchOnStale

But the underlying problem is that u want to describe both a Boolean and Time with the same flag, so would it make sense to split it instead?

staleTime: 20
refetchOnChange: true //or other

In this case the second option should have priority.

**Comment by alonbardavid** [comment]
Perhaps instead of naming it based on what the flag does, it'll be better to name it on what it doesn't do - it doesn't take from cache initially, or it ignores stales data.

Could be something like `maxAge` or `preventStale` or `requireInitial` ? `forceFirst` maybe?

**Comment by talolard** [comment]
> I understand that long names would usually drive people away from using the api, but `refetchOnMountOrArgChange` sounds beautiful (and perfectly descriptive) to me

+1
I understand what that API does and will thus use it, possibly correctly

**Comment by cephalization** [comment]
`refetchOnEffect`

**Comment by jamiehicks154** [comment]
RefetchOnStale

**Comment by hagmic** [comment]
I like the semantics of Apollo Clients `fetchPolicy`. Perhaps a `refetchPolicy` option could work for rtk-query, allowing for some future proofing as well. 

For expiration, I like `expires`, `maxAge` or `pollInterval` (if that’s what it’s doing, I’m unfamiliar with the implementation details).

**Comment by msutkowski** [comment]
Just to add in to this, this behavior **is not** _only for hooks_. You could also do this just by `dispatch(api.endpoints.getMyThing.initiate(undefined, { whateverMakesSense: 20 }))`. The other thing to consider is that immediately following this feature, we'll most likely add in support for `refetching` _(or whatever)_ for `refetchOnFocus`, `refetchOnReconnect`, etc. There are other common terms we haven't really consider yet, such as `revalidate`. 

In regards to some of the ideas like `fetchPolicy`, that makes sense when you have options like `cache-only`, `network-only`, `cache-first`, etc. Being that we're giving a boolean or numeric value as the options, those type of enums don't really seem to fit the bill in my opinion. They could, but we'd have to introduce additional options at that point, which would potentially confuse things further. 

The reason `refetchOnSubscribe` or `refetchOnUse` currently make sense _to me personally_, is that technically speaking, when a new hook is mounted or a user dispatches a relevant action, a `subscriber` is added to the internal tracking.

There is also the case that you could do `useWhateverQuery(1, { skip: dependentState, xWhateverY: 10 })`, which could be false upfront, then reevaluate when the `dependentState` updates. In this case, things like `maxAge`, `expires`, `refetchPolicy` etc etc don't really convey the behavior.

Also, thank you everyone for the input so far! Who would've thought naming a thing could be so... challenging? 😅

**Comment by giovannibenussi** [comment]
As other have suggested, I also think that there are two configurations in the place of one:

- Refetch data on prop change?
- Maximum Time To Live (TTL) for cached results.

However, I’m really confused why would want that when a prop change (in this case, a page change) doesn’t trigger a query. In React components/hooks I’d expect this.

Now, as a wrote this, it sounds like a use case is delay (e.g: when a user types on a search box), so you want to wait a bit before query again. Is this the use case?

Related with the on mount - on update thing, I think that is assumed on the React community that they should behave in a similar way. For example, you asume that data is going to be fetched when mounting. So maybe there’s no need to make a explicit reference. I’d focus on the reactive side.

**Comment by phryneas** [comment]
> As other have suggested, I also think that there are two configurations in the place of one:
> 
>     * Refetch data on prop change?
> 
>     * Maximum Time To Live (TTL) for cached results.
We have a "maximum TTL" for stuff that is not being used by any component (that data is just cleaned from the store) as well as a "polling" option that will just refetch a query every X seconds, so TTL use cases are pretty much already covered elsewhere.

This is really a "in this particular case, when this component wants something new (first render or changing to another api url/parameter), we want to consider something as stale which we otherwise wouldn't consider stale, so please refetch it.
> 
> However, I’m really confused why would want that when a prop change (in this case, a page change) doesn’t trigger a query. In React components/hooks I’d expect this.

Assume that you have two components side-by-side. Component A already shows page 2 and component B just changes from page 1 to page 2. That data is already in the cache, and apparently it's up-to-date - otherwise you wouldn't be displaying it right now, right?

Doing an automatic refetch of this data on component B's navigation would also update the data component A is already displaying, so that might even be unexpected/unwanted.

> 
> Now, as a wrote this, it sounds like a use case is delay (e.g: when a user types on a search box), so you want to wait a bit before query again. Is this the use case?

The main use case is "using the same hook in multiple components that are rendered at the same time and only triggering one query".

So you have three components that all call `usePostQuery(3)`, you want all these to have the same contents and not necessarily all of them to refetch every time one comes into view. (Especially when those are all rendered very soon after each other)

The default behaviour right now is that only data that is not already in the store is being fetched by default - and if no component uses said data, it is removed from the store after 60 seconds (configurable on a global level).
So you don't get unexpected updates and things plopping around just because a component is mounted and data is in sync everywhere.

These options we're discussing here would allow you to say "but if that data is older than X, I want it to be refetched" or "if this component is mounted, refetch that data, no matter what". This might be useful in some cases, but not required in all of them.


React-query has a similar option called `refetchOnMount` with similar default behaviour (refetch on mount if data is stale - we just never keep stale data, but throw it away once we consider it stale).

As for "regular refreshing", we also have the polling options - this would also work more reliably than "refetch on every render", as in a React applciation you don't really have any control over how often a component is rendered.

**Comment by asherccohen** [comment]
Ok with this new information the it looks like this option is "forcing" some default behaviour for an edge case.

forceRefetch
forceParallelRefetch
forceParallelRefetchOnStale

Ps. On a side note (and definetely for a different discussion) I have tested the polling feature and there could be space for improvement as devtools get very cluttered with an infinite list of /pending /fulfilled actions.
