### ISSUE TITLE
How to customise error type for queries and mutations?

### ISSUE THREAD

**Issue by ModPhoenix** [rtk-incubator/rtk-query#86]
For example api returns error like:

```ts
data: {
    code: string;
    validation_errors?: { code: string; field: string }[];
};
status: 401;
```

![image](https://user-images.githubusercontent.com/9993443/101177371-6a155a80-3650-11eb-8b14-6d29aa3a1b12.png)

Now i do so:

![image](https://user-images.githubusercontent.com/9993443/101177924-03447100-3651-11eb-91c7-57badbbd8711.png)

Is it possible to improve this somehow?

**Comment by phryneas** [comment]
The error is essentially dictated by the `fetchQuery`, so you can switch out the `FetchBaseQueryError` there - but the `SerializedError` will stay in that type union nonetheless, as that will be the error type for everything that is just thrown in fetchBaseQuery/onStart/onError/onSuccess without being handled properly.

If you know the format that will be returned with all non-2xx-status responses from your server, you could just cast your `fetchQuery as BaseQueryFn<string | FetchArgs, unknown, YourErrorType, {}>`.

Actually, I just notice, that we are not exporting `FetchArgs` (will do so in a future version!), so here's that type just for copy/paste right now:
```ts
interface FetchArgs extends RequestInit {
  url: string;
  params?: Record<string, any>;
  body?: any;
  responseHandler?: 'json' | 'text' | ((response: Response) => Promise<any>);
  validateStatus?: (response: Response, body: any) => boolean;
}
```

**Comment by msutkowski** [comment]
Going to close this due to inactivity. If you still have questions, let us know. This was covered in the 0.2 release, and there is relevant documentation here: https://rtk-query-docs.netlify.app/concepts/error-handling.
