### ISSUE TITLE
Opening the API to allow for custom React Context

### ISSUE THREAD

**Issue by Yurickh** [rtk-incubator/rtk-query#92]
## Context
- `react-redux` currently supports providing a custom context [during Provider creation](https://react-redux.js.org/api/provider#props) via the the `context` prop as well as in [its `createXXXHook` utilities](https://github.com/reduxjs/react-redux/blob/master/src/hooks/useSelector.js#L93);
- `rtk-query` hooks will [reach out to the default `ReactReduxContext` context](https://github.com/rtk-incubator/rtk-query/blob/next/src/buildHooks.ts#L3) with currently no option to override;
- This makes it so consumers of the `context` api can't use `rtk-query` in their existing projects (ohno).

## Question
Do you consider adding some kind of option to the `createAPI` API that would allow consumers to provide a custom context which would by the generated hooks to reach out to the store?

I'd be glad to contribute, but wanted to run the question through you first, as I imagine you might have some opinions on this topic.

**Comment by markerikson** [comment]
Out of curiosity, what's your use case for using an alternate context instead of the default `ReactReduxContext`?

**Comment by Yurickh** [comment]
In plain terms, we have multiple stores in our render tree, and each has its own context, so we don't conflict up when components reach out to state. 

I would love to go over the reasoning that brought us to this setup, but for this issue I think it's enough to know we tried multiple approaches before, and this one is working for us so far. It has been a two-year-long-ride :p~

**Comment by markerikson** [comment]
Ouch, yeah. 

This is low enough priority I don't think we're going to be trying to add it ourselves, but if you or someone else wants to try filing a PR to add that we could potentially get it in.

**Comment by phryneas** [comment]
I would put this off for a small moment. I'm thinking of splitting the react-specific stuff out, so we will probably have stuff like

* createApi.enhance(enhancer)
* enhanceWithHooks(options)
* createReactapi = createApi.enhance(enhanceWithHooks(options))

which would open the door for other enhancers for other frameworks and would allow us to ship a non-react-version of this for smaller bundle size in other frameworks.

Adding the custom context to the `options` for `enhanceWithHooks` would be a lot easier as that point than trying to get it in right now.

In the meantime, I'd almost recommend you use something like https://www.npmjs.com/package/patch-package to just force it in there.

**Comment by Yurickh** [comment]
Ah, thanks for the headsup! A bummer though, I'm almost good with [the changes](https://github.com/rtk-incubator/rtk-query/compare/next...Yurickh:feature/support-custom-context) 😅 

Totally understand the rationale for this though. Is this enhance api something that I could help pushing forward, or is my best bet to cross my fingers and wait? :)~

**Comment by phryneas** [comment]
I think this will be pretty soon. I want to finish the code generation before that, but I believe we'll have this in before we do a next release in a week or two.

As for helping out: I **really** appreciate the offer, but this is one of the places where I want 100% control of how the types play out as this might influence all kinds of architectural decisions down the road and I need to do some experimentation until I find the direction I want it to go specifically.

I'm sorry that you already have put time in, but on the other hand: you now almost have a fork that you can work with right now without waiting for another relase :sweat_smile:

**Comment by kahirokunn** [comment]
I heard that this issue was accomplished by the following pull request.
I'm very curious about this. Do you have any examples of its use :eyes:

https://github.com/rtk-incubator/rtk-query/pull/116

**Comment by phryneas** [comment]
Actually, #116 was just the "split up into modules" part.
I'll get to this today or tomorrow :)

**Comment by kahirokunn** [comment]
Thx!

**Comment by phryneas** [comment]
This is now covered here: https://rtk-query-docs.netlify.app/concepts/customizing-create-api#customizing-the-react-redux-hooks
