### ISSUE TITLE
Typescript typing autogenerated hook "data"

### ISSUE THREAD

**Issue by cole-robertson** [rtk-incubator/rtk-query#94]
I could not find an example for using the autogenerated query hooks with Typescript. Is there a way to type the data that is returned from this hook?

**Comment by phryneas** [comment]
Yes, as generic argument to `build.query`.

```ts
export const pokemonApi = createApi({
  reducerPath: 'pokemonApi',
  baseQuery: fetchBaseQuery({ baseUrl: 'https://pokeapi.co/api/v2/' }),
  endpoints: (builder) => ({
    getPokemonByName: builder.query<ApiReturnType, QueryArg>({
      query: (name) => `pokemon/${name}`,
    }),
  }),
});
```

For many, many more examples, see these tests:
https://github.com/rtk-incubator/rtk-query/blob/next/test/createApi.test.ts#L160-L283

**Comment by cole-robertson** [comment]
Thank you for pointing me in the direction, I appreciate it!
