### ISSUE TITLE
Prefetch immediately 

### ISSUE THREAD

**Issue by cole-robertson** [rtk-incubator/rtk-query#95]
In react-query, you can create and call a prefetch method without using a hook or any other context. I understand that Redux requires dispatching the event as it interacts with the Redux store, but I have the need to just call a prefetch method immediately without having to use the hook and then calling the function. The "dispatch" verbose solution seems like it might work, but would be a bit cumbersome to connect to my components each time I just want to prefetch right away.

**Comment by phryneas** [comment]
Yeah, but also that prefetch in react-query has to be called somwhere, so you're back to calling it in a `useEffect`, right?

So in react-query, you would have to do 
```js
useEffect(() => { 
  queryCache.prefetchQuery('user/5', () => fetch('/user/5'))
}
```

So you could do it multiple ways:
```js
const prefetchUser = usePrefetch('getUser');
useEffect(() => { prefetchUser(5) })
```

```js
const dispatch = useDispatch();
useEffect(() => { dispatch(api.internalActions.prefetchThunk('getUser', 5)) })
```

or, just before even rendering react

```js
store.dispatch(api.internalActions.prefetchThunk('getUser', 5))
```

Honestly, I don't really see how this is so much more cumbersome? 

But of course you could abstract that once:
```js
const usePrefetchImmediately = (endpoint, arg) => { 
  const dispatch = useDispatch();
  useEffect(() => { dispatch(api.internalActions.prefetchThunk(endpoint, arg)) })
}
```
and then just do
```js
usePrefetchImmediately('user', 5)
```
in your components

**Comment by cole-robertson** [comment]
That is exactly the solution I have done now, however the react-query solution is just a normal function actually, no hooks. I can use them anywhere in my application, without having to follow the rules of hooks. I am working in a older project where I am using RTK, and started to use react-query as well. 

I am just trying to see if everything I am doing in react-query can translate over to RTK query. 

I have made a similar function to your usePrefetchImmediately,( with the same name haha), but I am using usePrefetch inside it. Is there a way in typescript to get the union of string literals that represent your endpoints to pass into usePrefetch?

**Comment by msutkowski** [comment]
@cole-robertson Here is my go at typing this... It's possible Lenz might chime in here though with something better. 

```ts
type EndpointNames = keyof typeof api.endpoints; 

export function usePrefetchImmediately<T extends EndpointNames>(
  endpoint: T,
  arg: typeof api.endpoints[T] extends ApiEndpointQuery<infer Def, any> ? Parameters<Def['query']>[0] : any,
  options: PrefetchOptions = {}
) {
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(api.internalActions.prefetchThunk(endpoint, arg, options));
  }, []);
}
```

**Comment by phryneas** [comment]
Rereading that: it could be written a little simpler, using the `initiate` method as source for the second argument:

```ts

type EndpointNames = keyof typeof api.endpoints;

export function usePrefetchImmediately<T extends EndpointNames>(
  endpoint: T,
  arg: Parameters<typeof api.endpoints[T]['initiate']>[0],
  options: PrefetchOptions = {}
) {
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(api.internalActions.prefetchThunk(endpoint, arg, options));
  }, []);
}
```

**Comment by phryneas** [comment]
This should now also be covered by the `useQuerySubscription` hook. See the release notes for 0.2.0: https://github.com/rtk-incubator/rtk-query/releases
