### ISSUE TITLE
Autogenerated hooks not generated.

### ISSUE THREAD

**Issue by Aloysb** [rtk-incubator/rtk-query#97]
Hi team, 

A very interesting and promising package!
We're looking into integrating it into our app.

Unfortunately impossible to access the autogenerated hooks, even using the example straight out of the docs.

This is my file:

```js
import { createApi, fetchBaseQuery } from "@rtk-incubator/rtk-query";
import { APIEndpoint } from "~/api";

// Define a service using a base URL and expected endpoints
export const gymAPI = createApi({
  reducerPath: "gym",
  baseQuery: fetchBaseQuery({ baseUrl: `${APIEndpoint}` }),
  endpoints: (builder) => ({
    getGymByKey: builder.query({
      query: (key: number) => `gym/${key}`,
    }),
  }),
});

// Export hooks for usage in functional components, which are
// auto-generated based on the defined endpoints
export const {useGetGymByKeyQuery} = gymAPI;
```

```
Property 'useGetGymByKeyQuery' does not exist on type '{ reducerPath: "gym"; internalActions: InternalActions; reducer: Reducer<CombinedState<{ getGymByKey: QueryDefinition<number, BaseQueryFn<string | FetchArgs, unknown, FetchBaseQueryError, {}>, never, any, string>; },  [...]
```

Same issue using the example straight out of your documentation.

Keep up the good work! 👍

**Comment by phryneas** [comment]
I'm going to assume you are not on TypeScript 4.1 or your VSCode is not set to TS 4.1 - these hooks use a new TypeScript feature, and for older TS versions the hooks are there, but TypeScript does not know about them.

So you'll have to either upgrade your TypeScript or use the alternative `api.endpoints.getGymByKey.useQuery' hook that was generated to be compatible with older TS versions.

**Comment by Aloysb** [comment]
<img width="607" alt="Screen Shot 2020-12-09 at 5 57 49 pm" src="https://user-images.githubusercontent.com/17796338/101661010-120f9700-3a48-11eb-9c37-6e42c8ebb1ee.png">

Was actually replying to myself.
For those who have the same issue as me, it's written clearly on the first page of the documentation.

Currently upgrading TSC, it will probably solve the issue.

**Comment by Aloysb** [comment]
Sweet! That was the issue.

FYI this is my setup with Redux Persist, might be handy for someone else.

```js
const appReducer = combineReducers({
  users,
  routes,
  feeds,
  admin,
  [gymAPI.reducerPath]: gymAPI.reducer,
});

const persistedReducer = persistReducer(persistConfig, appReducer);

export const store = configureStore({
  reducer: persistedReducer,
  //This middleware is to avoid a serializable error in the console.
  middleware: getDefaultMiddleware({
    serializableCheck: false,
  }).concat(gymAPI.middleware),
});

export const persistor = persistStore(store);
```

Works like a charm! Thanks 🎉

**Comment by Aloysb** [comment]
I've spoken a bit fast.
The error is still error despite having upgraded Typescript (4.1.2), I still have the same issue

`Property 'useGetGymByKeyQuery' does not exist on type '{ reducerPath: "gym"; internalActions: InternalActions; reducer: Reducer<CombinedState<{ getGymByKey: QueryDefinition<number, BaseQueryFn<string | FetchArgs, unknown, FetchBaseQueryError, {}>, never, any, string>; }, never> & QueryStatePhantomType<...>, AnyAction>; ... 4 more ...; endpoints: { ...; }; }'.ts(2339)`

However, the hook do work as intended.

**Comment by phryneas** [comment]
Did you change your editor's TS version?

![image](https://user-images.githubusercontent.com/4282439/101671543-e8a93800-3a54-11eb-8132-a3fe286f3d1b.png)

**Comment by Aloysb** [comment]
🤦 - this was the case.
Thanks for you time, problem solved.
