### ISSUE TITLE
Make removal/refetch on invalidate/refetchOnX configurable

### ISSUE THREAD

**Issue by phryneas** [rtk-incubator/rtk-query#99]
In the spirit of https://react-query.tanstack.com/docs/guides/scroll-restoration we should maybe refetch them by default, but add a config option to remove instead?
So a `refetchUnmounted` option that kicks in both here and on invalidateEntities?

_Originally posted by @phryneas in https://github.com/rtk-incubator/rtk-query/pull/90#discussion_r540384737_

**Comment by Kirbyasdf** [comment]
I second this, and ask for a trace of what triggered it to occur in the logger

**Comment by phryneas** [comment]
I'm closing everything here now. If there's any need for further discussion, that should take place in a new issue over at https://github.com/reduxjs/redux-toolkit/
